### ISSUE TITLE
Feature request: please provide a tutorial how to build SPARTA on windows

### ISSUE THREAD

**Issue by GavrilenkovRK9** [sparta/sparta#107]
## Summary

Please provide a tutorial on how to build SPARTA on windows

## Type of Issue

Feature request

## Detailed Description 
Could you please make a tutorial how to build SPART on windows.
I figures out how to start cygwin, but when I type in make %machine% I just get a bunch of errors like "name_of_file.cpp->name_of_file.d - command not found"
Maybe I am choosing wrong type of %machine%

**Comment by stanmoore1** [comment]
@GavrilenkovRK9 can you please repost this on the SPARTA users mail list (see https://sparta.sandia.gov/mail.html)? I think you would get a better response there. Thank you.
