### ISSUE TITLE
Cut2D error

### ISSUE THREAD

**Issue by jborgida** [sparta/sparta#121]
## Summary

Singlet CLINES point not on cell border

## Type of Issue

Bug Report

## SPARTA Version (Bug Report)

Newest Version downloaded in Jan 2020

## Expected Behavior (Bug Report)

"This is an error when calculating how a 2d grid is cut or split by surface elements. It should not normally occur. Please report the issue to the SPARTA developers."

## Actual Behavior (Bug Report)

Tried to read a 2294 points/lines surface file written as a .txt to run a flow simulation over an axisymmetric version of the Mars pathfinder vehicle but some of the surfaces i guess had a problem, specifically surfaces 490-497 or something along those lines. I'm very new to SPARTA so I don't really know what to do here but I can add my files down below and maybe you get the same thing.

## Steps to Reproduce (Bug Report)

[https://www.dropbox.com/sh/1s6aksvhrvhjxha/AAA4gS2HckZX91SYLR1QhS5Ca?dl=0](url)

This link has all the files from my program. 
once you have the files in the right directory, i just run the command 

./spa_serial.exe < in.txt 

and then the error should pop up 
the data for the read surf file should be path.txt

If you can't manage to get to the files in the dropbox, send me an email and we can get on the phone to sort something out.

Sorry if I haven't provided enough info, it might be easier to describe over the phone or by email. 

Thanks
Jason B.

**Comment by stanmoore1** [comment]
@jborgida thanks for reporting. I went to that dropbox link, but I can't find any SPARTA files. Can you point me to the right directory in dropbox?

**Comment by stanmoore1** [comment]
@jborgida I was not able to get your files to reproduce this, can you upload them to this issue?

**Comment by stanmoore1** [comment]
Probably related to #7. Don't have a reproducer, so closing for now. Please reopen a new ticket if necessary.
