### ISSUE TITLE
Ambipolar bug

### ISSUE THREAD

**Issue by aborner1** [sparta/sparta#123]
## Summary

When running the "ambi" example with current master, the temperature eventually reaches unphysical values.

## Type of Issue

Bug Report

## SPARTA Version (Bug Report)

Current master (as of Feb. 4th 2020), but has been reproduced with versions going as far back as 5Sep18. Version 22Jun18 shows correct results. Bug was introduced by 2b038d8 .

## Expected Behavior (Bug Report)

The one from the log files in the "ambi" folder.

## Actual Behavior (Bug Report)

Both temperature and number of reported collisions for O and N electronic ionization reactions reach unphysical values at some point between 1000 and 2500 steps. This ambipolar bug has also been observed in other cases involving ionization.

## Steps to Reproduce (Bug Report)

Run "ambi" example for 5000 steps.

**Comment by aborner1** [comment]
@sjplimp @stanmoore1 I can help debug this if you'd like.

**Comment by aborner1** [comment]
Serial:
Step CPU Np Natt Ncoll Nsreact c_temp c_10[6] c_10[7] c_10[8] c_10[9] c_10[10] c_10[11]
       0            0   128584        0        0        0    180620.56            0            0            0            0            0            0
     100   0.56274319   128521      880      597        0     178379.3            0            0            0            0            0            0
     200    1.1713061   129012     1368      871        0    173896.52            0            1            0            0            2            0
     300     1.830034   130297     2412     1358        0    168741.68            2            1            0            3            5            0
     400    2.5857301   131781     4424     2103        0    163401.36            5            2            0           20           13            0
     500    3.4093311   133599     6899     3061        1     157828.8           10            1            7           60            7            0
     600    4.3278961   135559    11860     4211        0    152578.86           17            2           22          135           15            0
     700     5.364646   137568    19553     5490        0    148591.47           23            5           38          251           15            0
     800     6.553525   140068    31709     7288        0    141955.41           33            6           70          424           22            0
     900     7.880542   143227    46129     8750        0    144217.05           43            5          104          659           24            0
    1000    9.3747551   146785    10748     3930        2    135230.32           35            8          133          898           23            0

Gas reaction tallies:
  style tce #-of-reactions 45
  reaction O2 + N --> O + O + N: 2465
  reaction O2 + NO --> O + O + NO: 9
  reaction O2 + N2 --> O + O + N2: 1295
  reaction O2 + O2 --> O + O + O2: 122
  reaction O2 + O --> O + O + O: 1520
  reaction N2 + O --> N + N + O: 3165
  reaction N2 + O2 --> N + N + O2: 239
  reaction N2 + NO --> N + N + NO: 18
  reaction N2 + N2 --> N + N + N2: 1856
  reaction N2 + N --> N + N + N: 5485
  reaction NO + N2 --> N + O + N2: 503
  reaction NO + O2 --> N + O + O2: 14
  reaction NO + NO --> N + O + NO: 2
  reaction NO + O --> N + O + O: 426
  reaction NO + N --> N + O + N: 842
  reaction NO + O --> O2 + N: 52
  reaction N2 + O --> NO + N: 2262
  reaction O2 + N --> NO + O: 344
  reaction NO + N --> N2 + O: 294
  reaction O + N --> NO+ + e: 620
  reaction N + N --> N2+ + e: 675
  reaction O + O --> O2+ + e: 56
  reaction NO+ + N --> O + N2+: 8
  reaction N2+ + O --> N + NO+: 23
  reaction N2 + N+ --> N + N2+: 223
  reaction N2+ + N --> N2 + N+: 317
  reaction NO+ + N --> N2 + O+: 579
  reaction NO+ + O --> O2 + N+: 33
  reaction NO+ + O --> N + O2+: 3
  reaction O2+ + N --> O + NO+: 19
  reaction O2+ + N --> O2 + N+: 25
  reaction O+ + N2 --> O + N2+: 8
  reaction N2+ + O --> N2 + O+ : 519
  reaction O+ + NO --> O2 + N+ : 1
  reaction O + e --> O+ + e + e: 4
  reaction N + e --> N+ + e + e: 25



4 threads:
Step CPU Np Natt Ncoll Nsreact c_temp c_10[6] c_10[7] c_10[8] c_10[9] c_10[10] c_10[11]
       0            0   128584        0        0        0    180581.75            0            0            0            0            0            0
     100   0.29057884   128585      899      642        0    178387.96            0            0            0            0            0            0
     200   0.59071398   129143     1394      902        0    173808.96            0            0            0            0            2            0
     300   0.85121083   130288     2386     1365        0    168822.28            0            2            0            3            4            0
     400    1.1290159   131755     4338     2083        0    163591.19            3            4            3           25            7            0
     500    1.4450278   133496     7588     2901        1    158254.02           12            2           12           77           12            0
     600     1.831744   135457    12161     4015        0    152720.65           26            2           29          134           21            0
     700    2.2555048   137380    19833     5288        0    147526.64           23            6           53          266           21            0
     800     2.800159   139707    29535     6791        0    965451.89           29            5           68          432           21            0
     900    4.8177969   127824   135813     9035       33     85012733          756           39          481          483           57            0
    1000     5.447953   112878      140       57       21    8828393.1          391           47          160          179           53            0

Gas reaction tallies:
  style tce #-of-reactions 45
  reaction O2 + N --> O + O + N: 1990
  reaction O2 + NO --> O + O + NO: 6
  reaction O2 + N2 --> O + O + N2: 1333
  reaction O2 + O2 --> O + O + O2: 119
  reaction O2 + O --> O + O + O: 1328
  reaction N2 + O --> N + N + O: 3208
  reaction N2 + O2 --> N + N + O2: 340
  reaction N2 + NO --> N + N + NO: 32
  reaction N2 + N2 --> N + N + N2: 2318
  reaction N2 + N --> N + N + N: 5553
  reaction NO + N2 --> N + O + N2: 676
  reaction NO + O2 --> N + O + O2: 14
  reaction NO + NO --> N + O + NO: 2
  reaction NO + O --> N + O + O: 381
  reaction NO + N --> N + O + N: 756
  reaction NO + O --> O2 + N: 36
  reaction N2 + O --> NO + N: 1638
  reaction O2 + N --> NO + O: 328
  reaction NO + N --> N2 + O: 134
  reaction O + N --> NO+ + e: 596
  reaction N + N --> N2+ + e: 2057
  reaction O + O --> O2+ + e: 204
  reaction O + N --> NO+ + e: 596
  reaction N + N --> N2+ + e: 2057
  reaction O + O --> O2+ + e: 204
  reaction NO+ + N --> O + N2+: 19
  reaction N2+ + O --> N + NO+: 118
  reaction N2 + N+ --> N + N2+: 4501
  reaction N2+ + N --> N2 + N+: 4008
  reaction NO+ + N --> N2 + O+: 482
  reaction NO+ + O --> O2 + N+: 71
  reaction NO+ + O --> N + O2+: 6
  reaction O2+ + N --> O + NO+: 7
  reaction O2+ + N --> O2 + N+: 79
  reaction O+ + N2 --> O + N2+: 2
  reaction N2+ + O --> N2 + O+ : 331
  reaction O+ + NO --> O2 + N+ : 7
  reaction O + e --> O+ + e + e: 6080
  reaction N + e --> N+ + e + e: 19520

**Comment by aborner1** [comment]
Actually, if the case is ran long enough (> 1000 steps), the bug will appear for any number of ranks (even serial).

**Comment by aborner1** [comment]
As far as I can tell, the bug was introduced with version 5Sep18, as version 22Jun18 looks to give correct results.

**Comment by aborner1** [comment]
Bug was introduced by SHA-2b038d8

**Comment by aborner1** [comment]
Bug can be bypassed if "relax" keyword is set to "constant" instead of "variable".

**Comment by aborner1** [comment]
The bug is due to the following modification in react_bird.cpp:

// added MAX() limit, 24Aug18
tgamma(z+2.5-omega) / MAX(1.0e-6,tgamma(z+r->coeff[3]+1.5));

going back to 
tgamma(z+2.5-omega) / tgamma(z+r->coeff[3]+1.5);

solves the problem.

**Comment by aborner1** [comment]
The following reactions should be commented out of the air.tce file as their temperature exponent is below -1.5, which causes the gamma function to have a native argument, which is not acceptable for the TCE model:

N2+ + O --> N2 + O+ 
E A 0.0 0.000 4.118e-11 -2.2 1.148e-19

O + e --> O+ + e + e
I A 0.0 2.188e-18 6.4761E3 -3.78 -2.188e-18

N + e --> N+ + e + e
I A 0.0 2.322e-18 4.1513E4 -3.82 -2.322e-18

**Comment by zhangchonglin** [comment]
@aborner1 I think I encountered similar issue as you did and reported it here: https://github.com/sparta/sparta/pull/10#discussion_r243719589

**Comment by aborner1** [comment]
@zhangchonglin Yes, I agree. I think it is solved, I will push an update very soon.

**Comment by zhangchonglin** [comment]
@aborner1 Thanks for the confirmation and fix!
