### ISSUE TITLE
Equilibration issue when running with 1 cell

### ISSUE THREAD

**Issue by aborner1** [sparta/sparta#13]
## Summary

There seem to be a problem when running simple cases with one grid cell only (e.g. a simple relaxation to equilibrium).

## Type of Issue

Bug Report

## SPARTA Version (Bug Report)

22Jun18

## Expected Behavior (Bug Report)

When running relaxation case, the system should relax to the expected equilibrium temperature.

## Actual Behavior (Bug Report)

When running in 1 cell, the system does not relax to the equilibrium temperature. When running on more than 1 cell (e.g. 2x2x2), the system does relax to the predicted equilibrium temperature.

## Steps to Reproduce (Bug Report)

Run attached script, should not converge to equilibrium. Then, change number of cells to 2x2x: will reach equilibrium.

## Further Information, Files, and Links

Reproducible with discrete and continuum vibrational temperature models, as well as different molecules (CO2).

[air-species.txt](https://github.com/sparta/sparta/files/2470483/air-species.txt)
[air-vss.txt](https://github.com/sparta/sparta/files/2470484/air-vss.txt)
[in-N2relax.txt](https://github.com/sparta/sparta/files/2470485/in-N2relax.txt)

**Comment by stanmoore1** [comment]
@aborner1 I see what you mean, but I have no idea what could cause this issue. Maybe @sjplimp or @mgallis can take a look.

**Comment by stanmoore1** [comment]
According to @aborner1, this seems to be related to artifacts in the pRNG.
