### ISSUE TITLE
Problems with SPARTA codes for the rotational relaxation process

### ISSUE THREAD

**Issue by realprivate** [sparta/sparta#131]
## Summary

There may be a possible bug in SPARTA codes for rotational relaxation. (in "collide_vss.cpp")

## Type of Issue

Physics bug

## Detailed Description (Enhancement Suggestion)

In "collide_vss.cpp", when the rotational degrees of freedom of the choosing particle is 3, the code uses the function "sample_bl()" to do the B-L process, but it only uses the omega of the selected particle (params[sp].omega) to calculate the particle rotational energy. From the Bird's book, this parameter should be replaced by the "average omega" of the collision pair (aveomega), because the average translational degrees of freedom of the collision pair is (2.5-aveomega). The problem will lead to some errors when dealing with gas mixtures.

## SPARTA Version (Bug Report)

The bug is in the code "collide_vss.cpp" (line 470 to line 471), and the SPARTA version is the latest version. The function is:   sample_bl(random,0.5*species[sp].rotdof-1.0, 1.5-**params[sp].omega**);

## Expected Behavior (Bug Report)

The parameter used in the function "sample_bl()" should be the average omega of the collision pair (aveomega).

## Actual Behavior (Bug Report)

The parameter now used is the omega of the selected particle (params[sp].omega).

## Steps to Reproduce (Bug Report)

The bug is a theoretical one, so this part is blank.

## Further Information, Files, and Links

The reference text book is the Bird's book: Molecular Gas Dynamics and the Direct Simulation of Gas Flows. The relevant discussion about the bug is in the section 5.4 and 5.5 of the book.

**Comment by stanmoore1** [comment]
@realprivate thanks for reporting. I've asked @mgallis to take a look at this.

**Comment by stanmoore1** [comment]
@realprivate was this fixed by #28?

**Comment by realprivate** [comment]
> @realprivate was this fixed by #28?

Yes, I think so, because for the latest SPARTA version, the ω used in the function sample_bl() is "params[ip->ispecies][jp->ispecies].omega", which is specified for the collision pair.

**Comment by stanmoore1** [comment]
OK thanks.
