### ISSUE TITLE
Why check_neighbor_norm_2d/3d return before perform surface norm check

### ISSUE THREAD

**Issue by zhangchonglin** [sparta/sparta#143]
## Summary

_Why in `read_surf.cpp` files, functions `check_neighbor_norm_2d/3d` return before perform surface norm check_

## Type of Issue

_Queston_

## Detailed Description
I am looking at the `read_surf.cpp` file. I noticed in both [check_neighbor_norm_2d](https://github.com/sparta/sparta/blob/f7399fb3d7f7be3a8c7dadf3fe968c163c83100d/src/read_surf.cpp#L2126) and [check_neighbor_norm_3d](https://github.com/sparta/sparta/blob/f7399fb3d7f7be3a8c7dadf3fe968c163c83100d/src/read_surf.cpp#L2194) functions, you have a `return` statement:
```
if (distributed || !distributed) return;
```
before further actions in the code.

**2d:**
https://github.com/sparta/sparta/blob/f7399fb3d7f7be3a8c7dadf3fe968c163c83100d/src/read_surf.cpp#L2126-L2132

**3d:**
https://github.com/sparta/sparta/blob/f7399fb3d7f7be3a8c7dadf3fe968c163c83100d/src/read_surf.cpp#L2194-L2200

**Additional, is the follow code segment doing meaningful work?**

https://github.com/sparta/sparta/blob/f7399fb3d7f7be3a8c7dadf3fe968c163c83100d/src/read_surf.cpp#L2212-L2225

Thanks!

**Comment by stanmoore1** [comment]
>if (distributed || !distributed) return;

Looking at the comments above, I think this code needs additional work and is a placeholder for future work that hasn't yet been completed. @sjplimp could comment better.
