### ISSUE TITLE
Duplicate sentences in Fix_balance documentation

### ISSUE THREAD

**Issue by zhangchonglin** [sparta/sparta#148]
## Summary

Duplication in `Fix_balance` command documentation

## Type of Issue

_`Suggestion for an Enhancement`_

## Detailed Description

Looking at the documentation of `fix_balance` command, there seems to be some duplicate sentences in `fix_balance` document, as below:

https://github.com/sparta/sparta/blob/5b6c647c2ef2b58f07fd0748679b66aaa3c096a6/doc/fix_balance.html#L130-L151

## SPARTA Version

commit: 2cb84b5

**Comment by stanmoore1** [comment]
@zhangchonglin thanks for reporting.
