### ISSUE TITLE
One line bug in compute_tvib_grid leading to wrong discrete vibrational temperature

### ISSUE THREAD

**Issue by aborner1** [sparta/sparta#158]
## Summary

In current master, the output from the tvib/grid for the "vibrate" example is extremely different from the log file that is provided in the folder.

## Type of Issue

Bug Report

## SPARTA Version (Bug Report)

Current master https://github.com/sparta/sparta/commit/d5d1fda8e2d4b666dd862d31d7680ddaca77c797

## Expected Behavior (Bug Report)

The discrete vibrational temperature should be much closer to the classical temperature or the discrete temperature provided in the old log file than it is (closer to 2000 than 10000 K).

## Steps to Reproduce (Bug Report)

Run "vibrate" example with vibrate. To simplify, can also run a case with a diatomic (N2) the only has 1 vibrational mode. Results also appear to be wrong.

**Comment by aborner1** [comment]
It appears https://github.com/sparta/sparta/commit/c60d3e6d0b70d7a47264d0044a12a2c467aba8df was correct but the next release https://github.com/sparta/sparta/releases/tag/5Sep2018 was not. So it's been wrong for a long time!

**Comment by aborner1** [comment]
Release 4Jan19 https://github.com/sparta/sparta/commit/4620a1dd008d81aef99d1e605610f231422634e6 was correct but the following one 15Feb19 https://github.com/sparta/sparta/commit/f1a0341ce13a6636cd1e517a57faac1bd46d8b0c was wrong.

**Comment by aborner1** [comment]
[in-N2-tvib.txt](https://github.com/sparta/sparta/files/4637283/in-N2-tvib.txt)

**Comment by aborner1** [comment]
[log-15Feb19.txt](https://github.com/sparta/sparta/files/4637302/log-15Feb19.txt)
[log-4Jan19.txt](https://github.com/sparta/sparta/files/4637303/log-4Jan19.txt)
[in-N2-tvib.txt](https://github.com/sparta/sparta/files/4637304/in-N2-tvib.txt)

**Comment by aborner1** [comment]
The vibrational energy e_vib appears identical in outputs from both code versions, so the problem comes from the computation of the discrete vibrational temperature in tvib/grid.

**Comment by aborner1** [comment]
However, we still need to exclude atoms from the calculation, therefore:
      if (particles[i].evib == 0) continue;
      ispecies = particles[i].ispecies;
should be replaced by:
      ispecies = particles[i].ispecies;
      if (!(species[ispecies].vibdof)) continue;

**Comment by stanmoore1** [comment]
Pretty sure our regression tests caught this (I have the N2 test in the suite) but I though the change was a bugfix so I just re-blessed the test.

**Comment by aborner1** [comment]
The other line that was added for multimode (polyatomic) 
https://github.com/sparta/sparta/blob/7c54323a63ae77239771b01efc975fc0c60ffcd5/src/compute_tvib_grid.cpp#L320
also needs to be removed in order for CO2 to relax properly.

**Comment by aborner1** [comment]
Actually, this only works for case where there are only polyatomics, or no polyatomic at all. If diatomic and polyatomic (i.e. N2 and CO2) are mixed, the current approach does not work anymore and the vibrational temperature is wrong. I am afraid tvib/grid will have to be somewhat rewritten, the modeflag=0/1/2 does not seem to work in my opinion.

**Comment by aborner1** [comment]
The following code, although it could probably be written more elegantly, fixes the problem:

[compute_tvib_grid_cpp.txt](https://github.com/sparta/sparta/files/4698633/compute_tvib_grid_cpp.txt)

**Comment by sjplimp** [comment]
@aborner1 Are you saying the new attached file now works for all modes = 0/1/2,
and for mixtures, e.g. N2 + CO2 ?
@stanmoore1 What does the history say about who/why changed this
from working to non-working?  Possibly me, but I don't recall it

**Comment by aborner1** [comment]
@sjplimp That's correct, I do believe it now works for all cases. But I think there is a more elegant way to write the code, I took some shortcuts to make it work.

Also, looking back at the history, I do believe you made the change. I believe the goal was to exclude was to exclude atoms (evib = 0), but it is actually possible for molecules to have a zero vibrational energy in the discrete model, if their energy is too low to reach the first level. However, they do need to be accounted for in the temperature calculation.

**Comment by sjplimp** [comment]
@aborner1 ok - I will make a couple small edits and submit it as a PR - thanks for figuring
out this issue

**Comment by sjplimp** [comment]
@aborner1 please check the latest PR and verify it is correct

**Comment by stanmoore1** [comment]
Fixed by #165. Closing #158.
