### ISSUE TITLE
Issues in surf_collide_diffuse

### ISSUE THREAD

**Issue by aborner1** [sparta/sparta#167]
## Summary

SVN commit 2410 introduced a bug in surf_collide_diffuse for cases where the accommodation coefficient is < 1.0. Also, the vibrational energy assignment post surface collision is not handled properly for discrete vibrational energies (modes are not populated).

## Type of Issue

Physics issue

## SPARTA Version (Bug Report)

Current master since SVN commit 2410.

## Behavior (Bug Report)

Line https://github.com/sparta/sparta/blob/e7b60e67fbfecf6db8bfd631bad186d8780b31f0/src/surf_collide_diffuse.cpp#L209 and the following should not have been added. The particle's rotational and vibrational energy should remain unchanged for a case where the random number is larger than the accommodation coefficient. Those 2 lines should be removed.

Additionally, the post surface collision energy assignment is not handled properly for discrete vibrational energies. The same comment also applies to collides style TD.
The following line
https://github.com/sparta/sparta/blob/e7b60e67fbfecf6db8bfd631bad186d8780b31f0/src/surf_collide_diffuse.cpp#L167
should be replaced by:
  if (ip) {
     diffuse(ip,norm);
     if (modify->n_add_particle) {
      int i = ip - particle->particles;
      modify->add_particle(i,twall,twall,twall,vstream);
    }
  }

**Comment by aborner1** [comment]
Additionally, the post surface collision energy assignment is not handled properly for discrete vibrational energies.
The following line
https://github.com/sparta/sparta/blob/e7b60e67fbfecf6db8bfd631bad186d8780b31f0/src/surf_collide_diffuse.cpp#L167
should be replaced by:
  if (ip) {
     diffuse(ip,norm);
     if (modify->n_add_particle) {
      int i = ip - particle->particles;
      modify->add_particle(i,twall,twall,twall,vstream);
    }
  }

The same comment also applies to collides styles Impulsive, CLL and TD.

**Comment by sjplimp** [comment]
@aborner1 We agree on the first issue - will push a PR for that.  Not clear on the 2nd issue
you raise.  Are you saying something different should be done for particle I if particle J
exists?  Not something different to particle J (versus what is already done?)

**Comment by sjplimp** [comment]
@aborner1 Figured out a better way to ask my Q.  Why should modify->add_particle()
be invoked for particle I when it already existed before the surface collision?
That call is to trigger fixes to do something b/c there is a new particle added.
It is only the J particle that was added.

**Comment by stanmoore1** [comment]
@sjplimp @aborner1 did this get fixed, or is there still a remaining issue?

**Comment by aborner1** [comment]
@stanmoore1 @sjplimp First issue is still present in the code.

Regarding the second issue, maybe I did not express myself clearly enough when trying to describe the issue.
During a diffuse collision between particle i and a surface, "Particle::evib()" is called at the end of "SurfCollideDiffuse:diffuse()". However, "Particle::evib()" does not handle discrete vibrational energy assignment properly.
See note in "Particle::evib()":
  // for DISCRETE, only need set evib for vibdof = 2
  // mode levels and evib will be set by FixVibmode::add_particle()
So FixVibmode::add_particle() needs to be called, which is why I suggested doing the same as for particle j. I know that fix works, however, it might not be the logical way to handle this as no particle was "added".

**Comment by stanmoore1** [comment]
@aborner1 I submitted a PR for the first issue. For the second issue, do you know what other collide methods need to be modified. You mentioned `collide style TD`, what about `collide style CLL`, or others?

**Comment by aborner1** [comment]
@stanmoore1 I think CLL may be handled properly because of the way Krishnan wrote that particular function, but, yes, in theory all the styles that accommodate to the surface temperature should be edited for internal energy.

**Comment by stanmoore1** [comment]
@aborner1 can you review #262?

**Comment by stanmoore1** [comment]
Issue #2 is not easily fixed in the Kokkos version of `surf_collide diffuse` since it is calling a virtual function inside a `parallel_for`, so it now errors out if using `surf_collide diffuse` with `fix vibmode`. When I have time I'll try to get a better solution.

**Comment by aborner1** [comment]
@stanmoore1 Looks good to me. The Kokkos code does indeed look odd, but you are the expert so fine with me.

**Comment by stanmoore1** [comment]
>The Kokkos code does indeed look odd, but you are the expert so fine with me.

Surface reactions aren't yet supported with Kokkos, so that is why a lot of code is commented out...

**Comment by aborner1** [comment]
I see, makes sense then
