### ISSUE TITLE
Inelastic collision problems in SPARTA code

### ISSUE THREAD

**Issue by realprivate** [sparta/sparta#187]
## Summary

The issue discusses the inelastic collision bugs in SPARTA code, and it also puts forward a proposal for the code improvement.

## Type of Issue

Report bugs, and also give an enhancement suggestion

## Detailed Description (Enhancement Suggestion)

Up to now, there are still some bugs in SPARTA code (most probable in collide_vss.cpp) about the inelastic collision process. For instance, when simulating molecular gases in equilibrium (see attachments), setting the relax value to "variable" will cause the rotational temperature to be obviously wrong, and setting the vibrate value to "discrete" will cause the vibrational temperature to be obviously wrong. Only when setting the relax value to "constant", and vibrate value to "smooth" will lead to the correct result.

Besides, the SPARTA now still uses the serial implementation from Bird to handle non-reactive inelastic collisions. In this case, if both particles are selected for an inelastic collision, there is some degree of coupling between their relaxation process. Furthermore, when both rotational and vibrational relaxation processes are considered, sequential testing for rotational followed by vibrational inelastic collisions will inherently couple the rotational and vibrational relaxation processes. In order to reproduce the specified internal energy relaxation rates for a given energy mode and species interaction, it would be better if SPARTA used the particle selection method prohibit double relaxation (from Haas et al, 1994), to replace the current method.

## SPARTA Version (Bug Report)

It is the latest SPARTA version, sparta-6Jul20.

## Expected Behavior (Bug Report)

When simulating molecular gases in equilibrium, the final translational temperature Ttran, rotational temperature Trot and vibrational temperature Tvib should be approximately equal, regardless of how the relaxation parameters are set in the input file. 

## Actual Behavior (Bug Report)

When setting relax value to "variable", the Trot will be obviously smaller than Ttran and Tvib. And when setting vibrate value to "discrete", the Tvib will be obviously smaller than Ttran and Trot. Only when setting the relax value to "constant", and vibrate value to "smooth" will lead to the right result. 

## Steps to Reproduce (Bug Report)

The attachments below are the input files of the test case, which simulates the O2 gas in equilibrium. Changing the "collide" and "collide_modify" command will reproduce the problems above. The filename should be changed (air.vss, in.relax, air.species) before testing.

## Further Information, Files, and Links

[air_vss.txt](https://github.com/sparta/sparta/files/5172533/air_vss.txt)
[in_relax.txt](https://github.com/sparta/sparta/files/5172535/in_relax.txt)
[air_species.txt](https://github.com/sparta/sparta/files/5172536/air_species.txt)

**Comment by realprivate** [comment]
I think one possible reason about the error caused by "relax variable" setting is that, the SPARTA uses Parker model to calculate the variational rotational relaxation number, but the characteristic temperature Tr used in the calculation is the characteristic temperature of the "selected collision pair". According to the book of Boyd et al (2017), the Tr used in this calculation should be a cell-based translational temperature computed either at each timestep or using a running average of the cell temperature.
For the collision pair model, I suggest using the "Variable Probability Exchange Model" of Boyd (1990), where the probability of translational-rotational energy exchange is calculated directly from the collision energy of the colliding pair.

**Comment by ahilanezhilappar** [comment]
I tried to validate the SPARTA code for the flow of diatomic gas over a cylinder with existing results and I found the heat flux calculation is incorrect.  I simulated the same for a monoatomic gas and it is validating with stagnation point heat flux error of 7%. So I could narrow down the bug is in inelastic collisions. Can someone shed more light on this issue ? Is there a way to tackle this problem? Thanks

**Comment by mgallis** [comment]
Can you give us more details about the issue? How did you determine this error?
Thank you

Michael Gallis

On Jun 4, 2021, at 3:04 AM, ahilanezhilappar ***@***.***> wrote:

﻿

I tried to validate the SPARTA code for the flow of diatomic gas over a cylinder with existing results and I found the heat flux calculation is incorrect. I simulated the same for a monoatomic gas and it is validating with stagnation point heat flux error of 7%. So I could narrow down the bug is in inelastic collisions. Can someone shed more light on this issue ? Is there a way to tackle this problem? Thanks

**Comment by stanmoore1** [comment]
This issue seems very similar to #2.

**Comment by mgallis** [comment]
The fix for this will be checked in soon.

From: Stan Moore ***@***.***>
Reply-To: sparta/sparta ***@***.***>
Date: Monday, June 7, 2021 at 4:11 PM
To: sparta/sparta ***@***.***>
Cc: Michael Gallis ***@***.***>, Comment ***@***.***>
Subject: [EXTERNAL] Re: [sparta/sparta] Inelastic collision problems in SPARTA code (#187)


This issue seems very similar to #2<https://github.com/sparta/sparta/issues/2>.

**Comment by aborner1** [comment]
@realprivate When you use the discrete vibrational temperature, do you use "compute tvib/grid" or "compute grid tvib"? If you don't use the latter, the displayed vibrational temperature will not be the value that the code uses. As a matter of fact, we should have a warning message that lets the user know they should NOT use "compute grid tvib" with the discrete model (and vice-versa).

**Comment by realprivate** [comment]
> @realprivate When you use the discrete vibrational temperature, do you use "compute tvib/grid" or "compute grid tvib"? If you don't use the latter, the displayed vibrational temperature will not be the value that the code uses. As a matter of fact, we should have a warning message that lets the user know they should NOT use "compute grid tvib" with the discrete model (and vice-versa).

Yes, in the test case above, I use "compute grid tvib" after I use the discrete vibrational temperature.

**Comment by aborner1** [comment]
@realprivate Sorry, I actually made things even more confusing in my last comment. You are supposed to use “compute tvib/grid” if you use the discrete model, otherwise the temperature you print out is actually wrong.

**Comment by realprivate** [comment]
> @realprivate Sorry, I actually made things even more confusing in my last comment. You are supposed to use “compute tvib/grid” if you use the discrete model, otherwise the temperature you print out is actually wrong.

Thanks for your advice ! I will test this later.

**Comment by stanmoore1** [comment]
#268 fixed the variable rotational portion of this issue. However, I'm leaving this issue open since using `vibrate discrete` still gives vibrational nonequilibrium.

**Comment by stanmoore1** [comment]
@aborner1 I can add a warning when using `compute grid tvib` with the discrete model. However, I think using `compute tvib/grid` without the discrete model is handled correctly in the code, do you disagree?

**Comment by aborner1** [comment]
@stanmoore1 Nope, I definitely agree

**Comment by stanmoore1** [comment]
This issue should be fixed by #468.
