### ISSUE TITLE
Reaction count breakdown at the end of run does not update when doing multiple runs

### ISSUE THREAD

**Issue by aborner1** [sparta/sparta#191]
## Summary

When doing more than one run, the count of gas reactions at the end of the output file always outputs the count from the first run.

## Type of Issue

Bug Report

## SPARTA Version (Bug Report)

Latest master

## Expected Behavior (Bug Report)

The surface reactions count is updated properly, but the gas reactions count is not and always displays the values from the first run.

**Comment by stanmoore1** [comment]
I can reproduce this.
