### ISSUE TITLE
cut2d error on transverse line

### ISSUE THREAD

**Issue by timteichmann** [sparta/sparta#203]
## Summary

Currently when trying to run SPARTA in 2d with very simple geoemtries that have surf lines not aligned with the grid, the simulation will instantly crash with the error :` ERROR on proc 0: LP: No positive areas in cell (../cut2d.cpp:441)`.

## Type of Issue

**Bug Report**

## SPARTA Version (Bug Report)

20Nov2020 (happens for July version as well though)

## Expected Behavior (Bug Report)

No Cut2d error.

## Actual Behavior (Bug Report)

SPARTA crashes with aforementioned error:` ERROR on proc 0: LP: No positive areas in cell (../cut2d.cpp:441)`

## Steps to Reproduce (Bug Report)

Simple surf file for geometry:

data.geo
```
surf file

5 points
5 lines

Points

1 0.0 0.0
2 0.75 0.0
3 0.75 0.1
4 0.1 0.2
5 0.0 0.2

Lines

1 1 2
2 2 3
3 3 4
4 4 5
5 5 1
```

Simple input script:
```
seed            55555
global          surfmax 1000000

dimension       2
global          comm/sort yes gridcut 0.0001

boundary            o o p

create_box      -0.002 0.758 -0.002 0.208 -0.5 0.5

create_grid     76 21 1
balance_grid    rcb cell

global              fnum 1

read_surf       data.geo
group   left surf id 1
group   bot surf id 2
group   right1 surf id 3
group   right2 surf id 4
group   top surf id 5
```

Note, the particles should be INSIDE the box.

**Comment by stanmoore1** [comment]
Probably related to #7 and #137.

**Comment by stanmoore1** [comment]
If I push out one of the points by epsilon, then it runs fine:

```
Points

1 0.0 0.0
2 0.7499999999999999 0.0
3 0.7499999999999999 0.1
4 0.1 0.2
5 0.0 0.2
```

```
  0 0 = number of pushed cells
  115 0 = cells overlapping surfs, overlap cells with unmarked corner pts
  512 171 115 = cells outside/inside/overlapping surfs
  115 = surf cells with 1,2,etc splits
  0.117500000000001 0.1175 = cell-wise and global flow volume
  CPU time = 0.00199914 secs
  read/check/sort/surf2grid/ghost/inout/particle percent = 4.2576 2.05128 1.94395 80.8348 10.9123 4.79428 0.0596303
  surf2grid time = 0.001616 secs
  map/comm1/comm2/comm3/comm4/split percent = 15.2847 2.09501 8.79315 1.29832 2.65565 68.1174
```

**Comment by timteichmann** [comment]
Yeah, but for more complex cases this can be quite annoying, especially as it is not straightforward to identify all the points that create conflicts beforehand. Is there any way the code could be improved to better deal with these cases? Apparently they do occur rather frequently? I guess it would also be fine if SPARTA did automatically try to resolve these edge cases by pushing the points slightly internally and just emitting a warning message in the log if it had to do so?

**Comment by stanmoore1** [comment]
We are still debugging this (I wasn't suggesting shifting the points as a final solution but rather an debugging observation), will keep you posted.

**Comment by stanmoore1** [comment]
These changes also allow it to run:

```patch
diff --git a/src/cut2d.cpp b/src/cut2d.cpp
index d156f07..51b8ce8 100644
--- a/src/cut2d.cpp
+++ b/src/cut2d.cpp
@@ -31,6 +31,7 @@ enum{EXTERIOR,INTERIOR,BORDER,INTBORD};
 enum{ENTRY,EXIT,TWO,CORNER};              // same as Cut3d
 
 #define EPSCELL 1.0e-10    // tolerance for pushing surf pts to cell surface
+#define EPSILON 2.0e-16
 
 // cell ID for 2d or 3d cell
 
@@ -551,7 +552,7 @@ int Cut2d::build_clines()
     // some lines may not follow this rule, but majority should
     // cbox = cell center pt, cmid = line center pt, l2b = cbox-cmid
 
-    if (x[0] == y[0] && x[1] == y[1]) {
+    if (fabs(x[0] - y[0]) < EPSILON && fabs(x[1] - y[1]) < EPSILON) {
       cbox[0] = 0.5*(lo[0]+hi[0]);
       cbox[1] = 0.5*(lo[1]+hi[1]);
       cbox[2] = 0.0;

```

**Comment by stanmoore1** [comment]
So it is a numerical precision issue.

**Comment by timteichmann** [comment]
Thanks for the update!
