### ISSUE TITLE
Grid2paraview.py is not ready for new grid structure with no parents

### ISSUE THREAD

**Issue by aborner1** [sparta/sparta#204]
## Summary

Grid2paraview.py is not ready for new grid structure with no parents if reading from a grid file.

## Type of Issue

Bug Report

## SPARTA Version

20Nov20

## Expected Behavior

Grid2paraview.py should run without issues.

## Actual Behavior

Error message:
Traceback (most recent call last):
  File "grid2paraview.py", line 1290, in <module>
    find_chunking(chunking, grid_desc, args)
  File "grid2paraview.py", line 78, in find_chunking
    Cx = grid_desc["create_grid"][1]["Cx"]
KeyError: 'create_grid'

## Steps to Reproduce

Adapt a grid during a simulation and write the grid file, then try and run grid2paraview.py

**Comment by azacharos** [comment]
I had the same issue

**Comment by stanmoore1** [comment]
Fixed by #212, closing #204.
