### ISSUE TITLE
Nov 20 release, restart simulation crashed with transparent surface

### ISSUE THREAD

**Issue by zhangchonglin** [sparta/sparta#209]
## Summary

In `November 20` release, the combined `transparent` surface and `read_restart` caused code to crash at the beginning of a restarted simulation.

## Type of Issue

Bug report

## Detailed Description (Enhancement Suggestion)

Running the `November 20` release with the circle example (modified to write and read restart file, and also try the transparent surface feature) in the examples folder, the code crashed when running the restart simulation after reading the restart file:

```
Reading restart file ...
  restart file = 20 Nov 2020, SPARTA = 20 Nov 2020
  orthogonal box = (0 0 -0.5) to (20 10 0.5)
  400 grid cells
  109849 particles
  100 surf lines
  0 0 = number of pushed cells
  72 0 = cells overlapping surfs, overlap cells with unmarked corner pts
  256 72 72 = cells outside/inside/overlapping surfs
  72 = surf cells with 1,2,etc splits
  143.600044896042 143.600044896042 = cell-wise and global flow volume
  CPU time = 0.0135741 secs
  read/surf2grid/rebalance/ghost/inout percent = 94.5902 3.46717 0.00702568 1.44202 0.493554
Memory usage per proc in Mbytes:
  particles (ave,min,max) = 3.375 1.6875 5.0625
  grid      (ave,min,max) = 1.51379 1.51379 1.51379
  surf      (ave,min,max) = 0.0102997 0.0102997 0.0102997
  total     (ave,min,max) = 4.89948 3.21198 6.58698
Step CPU Np Natt Ncoll Nscoll Nscheck c_2[1] c_2[2] 
    1000            0   109849        0        0        0        0            0            0 
ERROR on proc 1: Collision cell volume is zero (../collide.cpp:482)
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 1
ERROR on proc 0: Collision cell volume is zero (../collide.cpp:482)
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
```
Somehow, I am not able to get a core dump file to trace the crash. Instead I modified the input scripts a little bit to change the transparent surfaces to regular surfaces (and to verify the crash is not caused by mistakes in the input scripts). In that case, the restarted simulation runs fine.

I did notice the `transparent` variable is not written/read in the `write_restart` or `read_restart` function within [surf.cpp](https://github.com/sparta/sparta/blob/master/src/surf.cpp), specifically here for 2d case, and similarly for 3d case:

https://github.com/sparta/sparta/blob/daf40fa4aefdb17b94c8a6f6b54bb7801976363c/src/surf.cpp#L3619-L3625
https://github.com/sparta/sparta/blob/daf40fa4aefdb17b94c8a6f6b54bb7801976363c/src/surf.cpp#L3680-L3688

## SPARTA Version (Bug Report)

`November 20` release with commit tag: 8e4b40c

## Expected Behavior (Bug Report)

The restarted simulation should successfully run without any issue.

## Actual Behavior (Bug Report)

Code crashed during the restart simulation.

## Steps to Reproduce (Bug Report)

The attached files contain the 2 cases I run:
 - transparent surface case: running with `./run_trans.sh`, the code will crash at the restart simulation
 - regular surface case: running with `./run_notran.sh`, the code runs fine.

Within the run scripts, it will point to respectively input scripts used.

## Further Information, Files, and Links

Cases to reproduce the crash is attached: 
[circle_restart_with_transparent_surface.tar.gz](https://github.com/sparta/sparta/files/5633223/circle_restart_with_transparent_surface.tar.gz)

**Comment by stanmoore1** [comment]
@zhangchonglin sorry for the delay. Just to check, are you reading a restart file generated by the old code, or an old restart file from the previous version? The latest release broke restart backwards compatibility, so the latter is expected to crash.

**Comment by stanmoore1** [comment]
I tried the reproducer. With no transparent surfaces, it runs fine. With transparent surfaces, I get `ERROR on proc 0: Collision cell volume is zero (../collide.cpp:482)` after reading in the restart file:

```
Reading restart file ...
  restart file = 20 Nov 2020, SPARTA = 20 Nov 2020
  orthogonal box = (0 0 -0.5) to (20 10 0.5)
  400 grid cells
  109849 particles
  100 surf lines
  0 0 = number of pushed cells
  72 0 = cells overlapping surfs, overlap cells with unmarked corner pts
  256 72 72 = cells outside/inside/overlapping surfs
  72 = surf cells with 1,2,etc splits
  143.600044896042 143.600044896042 = cell-wise and global flow volume
  CPU time = 0.0516171 secs
  read/surf2grid/rebalance/ghost/inout percent = 90.7879 5.18019 0.0969986 1.99909 1.93581
Memory usage per proc in Mbytes:
  particles (ave,min,max) = 3.375 1.6875 5.0625
  grid      (ave,min,max) = 1.51379 1.51379 1.51379
  surf      (ave,min,max) = 0.0102997 0.0102997 0.0102997
  total     (ave,min,max) = 4.89948 3.21198 6.58698
Step CPU Np Natt Ncoll Nscoll Nscheck c_2[1] c_2[2] 
    1000            0   109849        0        0        0        0            0            0 
ERROR on proc 0: Collision cell volume is zero (../collide.cpp:482)
```

**Comment by stanmoore1** [comment]
I talked to @sjplimp and we agree that the transparent flag should be included in the restart file. I'll submit a PR.

**Comment by zhangchonglin** [comment]
Thanks Stan! @stanmoore1. I noticed in your PR #213, you added transparent flag to 2d simulation case (lines). Should you also do that for 3d  simulation case (triangle surfaces)?

**Comment by stanmoore1** [comment]
>Should you also do that for 3d simulation case (triangle surfaces)?

@zhangchonglin Yes, I totally forgot that, thanks!
