### ISSUE TITLE
Incorrect result when using "fix emit/face" in parallel 

### ISSUE THREAD

**Issue by rkcroc** [sparta/sparta#228]
## Summary

I get different numbers of particles emitted when running the same problem parallel versus serial.

## Type of Issue

Bug Report

## Detailed Description (Enhancement Suggestion)

_Explain how you would like to see SPARTA enhanced, what feature(s) you are looking for, provide references to relevant background information, and whether you are willing to implement the enhancement yourself or would like to participate in the implementation_

## SPARTA Version (Bug Report)

Using master (37a47711)

## Expected Behavior (Bug Report)

Same result in serial and parallel.

## Actual Behavior (Bug Report)

Different number of emitted particles, starting after 200K steps.

## Steps to Reproduce (Bug Report)

Run attached in serial, and 4 procs (`mpirun -np 4`). Compare the total number of particles added to the domain per step. For serial, it is always the same (100). For parallel, during steps 1-2000 it is correct (100), while thereafter it increases (to 151, and later 150). I attach CSV files with these numbers calculated explicitly to this issue. I can also supply log files as necessary.

## Further Information, Files, and Links

The input file, `in.duct_free` is attached here.
In addition, here is info on my system:
- WSL2 Ubuntu 20.04 LTS (Windows 10)
- OpenMPI 4.0.3 (as reported by `apt list`. CMake reports version 3.1)
- gcc/g++ 9.3.0
[duct_free.zip](https://github.com/sparta/sparta/files/5974526/duct_free.zip)
[duct_l1_np4_debug.xlsx](https://github.com/sparta/sparta/files/5974528/duct_l1_np4_debug.xlsx)
[duct_l1_ser_debug.csv.gz](https://github.com/sparta/sparta/files/5974529/duct_l1_ser_debug.csv.gz)

**Comment by rkcroc** [comment]
Sorry, meant to attach same file type for both spreadsheets. Including CSV here; can sent excel sheets if necessary.
[duct_l1_np4_debug.csv.gz](https://github.com/sparta/sparta/files/5974533/duct_l1_np4_debug.csv.gz)

**Comment by stanmoore1** [comment]
DSMC is inherently stochastic and based on statistics, so this is not necessarily a bug. The pseudo random number generator (pRNG) is SPARTA depends on the number of MPI ranks. So changing the number of MPI ranks is the same as changing the starting `seed` for the pRNG, and you will get two slightly different (but equally valid) simulations if you run serial vs parallel. D

**Comment by rkcroc** [comment]
Stan,
Thanks for the prompt response.
I do not believe this is a stochasticity issue. If that were the case, the numbers of particles inserted would have been more random. If you look at the input deck, you'll see that i am requesting 100 particles emitted per timestep. The parallel run did exactly this for the first 2000 steps, but then switched over to 151 particles. This doesn't appear to me the work of randomness.
Is it possible to keep the emitting face (xlo) entirely on one processor? If so, then I can run np=4 both with the emitting face on one proc and with it on several, to see if that affects the outcome. That might provide some guidance.
What do you think?

**Comment by aborner1** [comment]
@rkcroc Are you using the Kokkos compiled version for these tests?

**Comment by stanmoore1** [comment]
>If you look at the input deck, you'll see that i am requesting 100 particles emitted per timestep. The parallel run did exactly this for the first 2000 steps, but then switched over to 151 particles. This doesn't appear to me the work of randomness.

OK we'll take a look.

**Comment by rkcroc** [comment]
@aborner1 No

**Comment by stanmoore1** [comment]
I'm looking at this now. It is suspicious that you rebalance every 2000 steps and the issue happens on step 2001, could be related. I see you are also using the "twopass" option for fix emit, which is a different codepath than not using that flag.

**Comment by stanmoore1** [comment]
I've confirmed this is related to `fix balance`, but not to `twopass`.

**Comment by stanmoore1** [comment]
@rkcroc This seems to fix the issue. I'll run this by @sjplimp and see what he thinks.

```patch
diff --git a/src/fix_emit.cpp b/src/fix_emit.cpp
index 55f9cf3..7e76535 100644
--- a/src/fix_emit.cpp
+++ b/src/fix_emit.cpp
@@ -103,7 +103,7 @@ void FixEmit::start_of_step()
 
 void FixEmit::grid_changed()
 {
-  create_tasks();
+  init();
 }
 
 /* ----------------------------------------------------------------------
```

**Comment by stanmoore1** [comment]
@rkcroc can you try #229, it should fix this issue.

**Comment by rkcroc** [comment]
@stanmoore1 Yes, I now get the expected result for the input deck I sent, with 4 MPI ranks.
Thanks much.

**Comment by stanmoore1** [comment]
@rkcroc thanks for the bug report and reproducer script.
