### ISSUE TITLE
Reg : create_grid levels and adapt_grid with distsurf/grid

### ISSUE THREAD

**Issue by rampsv08** [sparta/sparta#254]
## Summary

Hi, 
    I have an issue in create_grid command when passing along with levels and 
    second issue is on adapt_grid.
    For simplicity I choose the examples/sphere case. 

## Type of Issue
Issue 1 :
create_grid         20 20 20 **levels 2 level 2 * * * 2 2 3**

ERROR: Illegal create_grid command (../create_grid.cpp:188)

when I check the source code, it look like it never enter the if loop 
line 114 :  else if (strcmp(arg[iarg],"levels") == 0) {...........}
line 188 :  else error->all(FLERR,"Illegal create_grid command"); 

Is the input command which I gave is correct ?
I am not able to sort out this.

Issue 2: 
           run                 1000
           compute        1 distsurf/grid all dir 1 0 0
           adapt_grid      refine value c_1 0.5 0.0 thresh less more  
           run 1000

ERROR:  compute distsurf/grid command surface group does not exist (../compute_distsurf_grid.cpp:49) 
           
 So I changed the above command like (all surface ID)
           run                 1000
           compute        1 distsurf/grid all **all**
           adapt_grid      refine value c_1 0.5 0.0 thresh less more
           run 1000         
Then result is 
         Adapting grid ...
            no grid adaptation performed

So I am not able to understand the adaptation. 
        I tried using  
          **adapt_grid all refine particle 10 50**   but still no grid adaptation is performed.

Is it possible to have input script on 3d grid adaptation using particles or nrho?

[in.sphere.adapt.txt](https://github.com/sparta/sparta/files/6545822/in.sphere.adapt.txt)
[in.sphere.levels.txt](https://github.com/sparta/sparta/files/6545823/in.sphere.levels.txt)

Regards
Vignesh Ram

**Comment by stanmoore1** [comment]
This was due to typos in the doc page (see my response on the mail list), which are fixed by #258 and #259. Closing this issue.
