### ISSUE TITLE
Tvib/grid wrong with multi-species mixture

### ISSUE THREAD

**Issue by aborner1** [sparta/sparta#26]
## Summary

The vibrational temperature computed by Tvib/grid is wrong in the case of a mixture contained both a polyatomic and an atom.

## Type of Issue

Bug Report

## SPARTA Version

10Dec18 (latest merge)

## Expected Behavior

For an equimolar mixture of O2 and O, the vibrational temperature of the the mixture and that of O2 should be equal.

## Actual Behavior

For an equimolar mixture of O2 and O, the mixture vibrational temperature is half of the O2 vibrational temperature, meaning that in the computation of Tvib, the total number of molecules rather than that of polyatomics that carry vibrational energy is used.

## Steps to Reproduce

Run attached script.

##  Files

[in-O2-O-tvib.txt](https://github.com/sparta/sparta/files/2665334/in-O2-O-tvib.txt)

**Comment by stanmoore1** [comment]
@aborner1 this does look like a bug.

**Comment by stanmoore1** [comment]
@aborner1 I believe I fixed this in #27, can you double check?

**Comment by aborner1** [comment]
@stanmoore1 Can confirm the bug appears fixed for both serial and MPI runs, at least for the script that I submitted.
