### ISSUE TITLE
Cannot have more than 32 surface groups

### ISSUE THREAD

**Issue by VirgileCharton** [sparta/sparta#260]
Hello,

I read that SPARTA handles a maximum of 32 surface groups: 31 user defined and a default group called "all". I am using an inflow condition with X different gaz conditions emitted from X different surfaces. Thus, X is the number of boundary conditions I want to use. I need to set X > 32, which is not allowed by SPARTA if I understand correctly. 

After a quick look to the code, even changing the 32 MAXGROUP limit does not enable the use of more than 32 boundary conditions. Apparently, the 32th group has to be the "all" one, hence regrouping all the other which means that the 32th surface boundary condition will emit all the gaz associated with all the boundary conditions instead of only the 32th one. 

I though it could be simple to set the maximum number of boundary conditions above 32 because I assumed that this 32 maximum was written as a fixed table size somewhere in the code. However, i find that this is not that easy. Is there a way to change this limitation and fix it to 100 for exemple ?

For exemple, setting MAXGROUP to 320 instead of 32 in surf.cpp does allow the creation of more than 32 groups. However, if the first 31 groups are correctly defined with the corresponding emitting surface boundary condition, the 32th contains all the remaining surfaces and then the 33th to 60th show a wrong surface count. Here is a sample of the output file, from a calculation where I define 61 different surface boundary conditions and where the 60th first condition should contain only one surface :

1 surfaces in group groupe1
1 surfaces in group groupe2
1 surfaces in group groupe3
1 surfaces in group groupe4
1 surfaces in group groupe5
1 surfaces in group groupe6
1 surfaces in group groupe7
1 surfaces in group groupe8
1 surfaces in group groupe9
1 surfaces in group groupe10
1 surfaces in group groupe11
1 surfaces in group groupe12
1 surfaces in group groupe13
1 surfaces in group groupe14
1 surfaces in group groupe15
1 surfaces in group groupe16
1 surfaces in group groupe17
1 surfaces in group groupe18
1 surfaces in group groupe19
1 surfaces in group groupe20
1 surfaces in group groupe21
1 surfaces in group groupe22
1 surfaces in group groupe23
1 surfaces in group groupe24
1 surfaces in group groupe25
1 surfaces in group groupe26
1 surfaces in group groupe27
1 surfaces in group groupe28
1 surfaces in group groupe29
1 surfaces in group groupe30
1 surfaces in group groupe31
63 surfaces in group groupe32
2 surfaces in group groupe33
2 surfaces in group groupe34
2 surfaces in group groupe35
2 surfaces in group groupe36
2 surfaces in group groupe37
2 surfaces in group groupe38
2 surfaces in group groupe39
2 surfaces in group groupe40
2 surfaces in group groupe41
2 surfaces in group groupe42
2 surfaces in group groupe43
2 surfaces in group groupe44
2 surfaces in group groupe45
2 surfaces in group groupe46
2 surfaces in group groupe47
2 surfaces in group groupe48
2 surfaces in group groupe49
2 surfaces in group groupe50
2 surfaces in group groupe51
2 surfaces in group groupe52
2 surfaces in group groupe53
2 surfaces in group groupe54
2 surfaces in group groupe55
2 surfaces in group groupe56
2 surfaces in group groupe57
2 surfaces in group groupe58
2 surfaces in group groupe59
2 surfaces in group groupe60
4 surfaces in group groupe61

The groups, associated mixture and surface id are defined in the attached file as 'groupe_B', 'mixture_B', 'emit_B'. According to these input settings, each groups should be associated to one boundary condition which is defined by one surface except the 61th.

In order to quickly reproduce the issue, I also attached the input file called 'input',  the geometry file 'geom_B' and the species file 'air.species' / 'air.vss'.

[file_input.zip](https://github.com/sparta/sparta/files/6576830/file_input.zip)

Thank you very much for your attention.
Regards,
Virgile Charton

**Comment by VirgileCharton** [comment]
Wrong input file.. Here is the good one:

[Input_files.zip](https://github.com/sparta/sparta/files/6577005/Input_files.zip)

**Comment by stanmoore1** [comment]
The 32 limit comes from using a bitmask on a 32 bit integer, so the number of groups cannot be easily extended, i.e. by simply changing a compile-time variable in the code. There may be a different workflow to get the desired behavior, this question comes up often in LAMMPS, which has the same 32 group limit.

**Comment by stanmoore1** [comment]
E.g. https://sourceforge.net/p/lammps/mailman/message/26209504/. @sjplimp could have some ideas on how to workaround the limitation.

**Comment by stanmoore1** [comment]
@VirgileCharton I talked to @sjplimp and he suggested writing your own fix that could use surface ids. Increasing the number of groups in SPARTA is not practical due to using a bitmask.

**Comment by stanmoore1** [comment]
I'm closing this issue, but feel free to post questions on the SPARTA mail list if you need help extending SPARTA.

**Comment by VirgileCharton** [comment]
Hi,
Thanks again for your suggestion. I tried with region keyword from emit/surf : my goal is to emit particules from more than 32 inflow boundaries. Instead of using 32 groups, I use one with all the surf corresponding to the inflows and define a region box for each emit/surf so that they only emit through surf defined by the region box. The number of region box is unlimited so that works for me. However, I might try to write my own fix that use directly surface ids, which is much more practical.
