### ISSUE TITLE
Paraview issue with SPARTA Feb2021 release 

### ISSUE THREAD

**Issue by bjohn-github** [sparta/sparta#264]
## Summary

grid2paraview.py not producing the .vtu file, when using the read_grid option in the grid description text file.

## Type of Issue

Bug Report

## SPARTA Version (Bug Report)

Feb2021 release

# Actual Behavior (Bug Report)

There seems to be a problem with paraview visualisation of the grid and results with the Feb2021 release, which is not present in previous versions like Jan20 release.  The problem is specifically for grid2paraview.py, when using the read_grid option in the grid description text file. It works if we use the create_grid option in the text file, but not with the read_grid option, as in previous versions like Jan20.
 
## Steps to Reproduce (Bug Report)

 I have attached a test case, which is a slightly modified version of the default ‘circle’ test case, with just the write_grid and dump commands added. I tried to generate the paraview grid file as – “pvpython grid2paraview.py grid.txt circle_grid -r GridTemp.1000”. 
 
All the relevant files are in the attached test case and I am using the latest grid2paraview.py from Feb2021 version. The created circle_grid directory has only a .pvtu file, but no .vtu file. When I try to open the .pvtu file in paraview, it gives me an error – ‘File for piece 0 cannot be read’.
[circle_test.zip](https://github.com/sparta/sparta/files/6664754/circle_test.zip)

**Comment by stanmoore1** [comment]
@tjotaha any ideas?

**Comment by tjotaha** [comment]
@stanmoore1 I was not able to reproduce this test case. I keep getting a .pvtu file along with a .vtu file. What version of ParaView was used when running pvpython? Was this on Windows? I'm using a Linux machine to try and reproduce.

**Comment by aborner1** [comment]
@tjotaha @stanmoore1 I have found that this happens if you try and post-process without a dump file, i.e. just the grid: you may want to try "pvpython grid2paraview.py grid.txt circle_grid".

**Comment by tjotaha** [comment]
@aborner1 I tried running the command without the dump file. I still get a working .pvtu and .vtu file.  Could I get some details about your ParaView version and platform?

**Comment by aborner1** [comment]
I was running on Mac OS 10.15 and Paraview 5.9.0-RC2.

**Comment by tjotaha** [comment]
It looks like it is a Mac related issue. I get a hang when I try to run pvpython from the terminal. This is using a download of ParaView 5.9 from the Kitware site.

**Comment by bjohn-github** [comment]
I use linux Opensuse and get issues only on using the Feb2021 release. As mentioned if the grid.txt file is specified as below (i.e. using the ‘read_grid viz.out’ instead of ‘create_grid 20 20 1’), I face the issues I mentioned. If we use the ‘create_grid 20 20 1’ option, then there are no issues. For both cases, I specify pvpython grid2paraview.py grid.txt circle_grid -r GridTemp.1000. The in.circle and all other files is already in the attached zip file.

Grid.txt file
-----------------
dimension       2
create_box          0 10 0 10 -0.5 0.5
read_grid              viz.out

**Comment by tjotaha** [comment]
Could you try the attached grid2paraview.py on this test case and report any error output?  Thanks.

[grid2paravew.zip](https://github.com/sparta/sparta/files/6696471/grid2paravew.zip)

**Comment by bjohn-github** [comment]
The error using the given grid2paraview.py is below. This is when using the ‘read_grid  viz.out’ option in the grid.txt file. With ‘create_grid 20 20 1’ option in the grid.txt file, there are no issues again.

Processing  1  grid chunk(s).
Traceback (most recent call last):
  File "grid2paraview.py", line 1472, in <module>
    args.paraview_output_file)
  File "grid2paraview.py", line 220, in create_and_write_grid_chunk
    grid_desc, time_steps_dict, output_file)
  File "grid2paraview.py", line 242, in process_grid_chunk
    read_grid_file(grid_desc, chunk_info)
  File "grid2paraview.py", line 372, in read_grid_file
    for dashed_id in sgf:
TypeError: instance has no next() method

**Comment by tjotaha** [comment]
Okay. It looks like the issue is related to a Python 2 and 3 incompatibility with the next iterator.  Please try the attached grid2paraview.py. It should work with both Python 2 and 3. If this fix works, I'll open a pull request to get this change in Sparta master.

[grid2paraview_fixed_python2.zip](https://github.com/sparta/sparta/files/6696884/grid2paraview_fixed_python2.zip)

**Comment by bjohn-github** [comment]
Yes, It does work now. Thanks!
