### ISSUE TITLE
create_grid issue

### ISSUE THREAD

**Issue by bjohn-github** [sparta/sparta#265]
## Summary
create_grid command with levels of refinement gives error with Feb21 release.

_Please provide a brief description of the issue_

## Type of Issue

'Bug Report'?

## Detailed Description (Enhancement Suggestion)

_create_grid 20 20 1 levels 2 level 2 * * * 2 2 1_ instead of _create_grid 20 20 1_ throws an error- "ERROR: Illegal create_grid command (../create_grid.cpp:188)"

 Please double check this.

## SPARTA Version (Bug Report)

Feb21 release.

**Comment by stanmoore1** [comment]
@bjohn-github You need to use the `subset` command, not `level`. The command syntax changed, but there was a typo in the docs.

```
  subset args = Ilevel Px Py Pz Cx Cy Cz
    Ilevel = which level(s) to define, see syntax below
    Px Py Pz = extent of parent cells in each dimension in which to create child cells
    Cx Cy Cz = size of child sub-grid in each dimension within parent cells
```

**Comment by stanmoore1** [comment]
The docs will be updated when the next release is pushed. Closing #265.

**Comment by thunderbird-98** [comment]
Could you reply to me with a correct example that uses the subset keyword, instead of levels?
Thanks
