### ISSUE TITLE
NaNs in Mean Free Path

### ISSUE THREAD

**Issue by kjhigdon** [sparta/sparta#3]
## Summary

Negative temperatures lead to NaNs in the mean free path calculation.

## Type of Issue

Bug Report

## Detailed Description

Negative temperatures calculated in a cell result in the mean free path calculation to fail. Negative temperatures result when there's only one particle in a cell. In this case, the temperature is calculated, but should result in zero. Due to machine precision, the temperature is likely to have some very small positive or negative value. Leading to the mean free path issue.

This could cause problems in grid refinement based on mean free path.

## SPARTA Version 

https://github.com/sparta/sparta/blob/45e17cdbda3845e40ed5aaf44399323c365b2941/src/compute_lambda_grid.cpp#L325

## Expected Behavior

In this case the mean free path is not defined and could be set to `BIG`. Also, the temperature should probably be set to 0.

## Actual Behavior

NaNs and negative temperature.

## Potential Fixes
FIX1
Change:
    `else if (tempwhich == NONE || temp[i] == 0.0)`
To:
    `else if (tempwhich == NONE || temp[i] > epsilon)`

**Note: Using `==` to compare floats should be avoided in most cases. This could be an issue in other places throughout the code.**

FIX2
Change the translational temperature calculation to ignore cases were the number of particles is one or zero.

## Steps to Reproduce (Bug Report)

Run a case where the number of particles per cell is low or has a very low density region.

**Comment by stanmoore1** [comment]
@kjhigdon thanks for reporting this issue. Could you post an "as small as possible" input deck for SPARTA that reproduces this issue? That would help a lot.

**Comment by kjhigdon** [comment]
@stanmoore1 I've attached the files for a case that generates NaNs. The NaNs are observed both in the log.sparta file as a global value and in several of the sim_grid_out.* files generated by running the case. This was a test case that I ran a couple weeks ago. Sorry if there's some useless processes in my in.circle input deck.

[mfp_issue.zip](https://github.com/sparta/sparta/files/2291779/mfp_issue.zip)

**Comment by stanmoore1** [comment]
@kjhigdon awesome thanks!

**Comment by stanmoore1** [comment]
@kjhigdon I can reproduce this.

**Comment by kjhigdon** [comment]
On a side note, a possible enhancement for the mean free path calculation would be to calculate the mean free path from the mixture definition. In the current calculation, a single reference species must be chosen in the input file. For a highly reactive flow, such as a hypersonic reentry case, the pre-shock and post-shock mixtures could be drastically different so choosing a single species could be difficult.

**Comment by stanmoore1** [comment]
Fixed in #296, see https://github.com/sparta/sparta/pull/296/files#diff-838c8ab9e71ab92827e3c963f2f164c11cfe3a9a437940ecf96a5156edf7d0cfL240.

Closing #3.
