### ISSUE TITLE
Test Suite Failures

### ISSUE THREAD

**Issue by ebolandrtx** [sparta/sparta#330]
## Summary

Sparta January 2022 build has a set of failures in the test suite.

## Type of Issue

Bug/Information Report 

## SPARTA Version (Bug Report)

January 7, 2022

## Expected Behavior (Bug Report)

Test Suite Passes

## Actual Behavior (Bug Report)

Failures found in collideInterspeices and thermostat tests.

**Comment by stanmoore1** [comment]
@ebolandrtx can you provide more details--how are you testing, what exact version of the code, etc? We have regression tests that are passing as well as the GitHub pull request tests.

**Comment by ebolandrtx** [comment]
Hi Stan,

We are using the through -DSPARTA_CTEST_CONFIGS="PARALLEL;SERIAL" \
and testing with ctest -C PARALL and ctest -C SERIAL

The version of the code is the most recent - January 7th 2022 release.

**Comment by ebolandrtx** [comment]
FYI - i am using the Intel 2021.2 compiler) with MKL and MPI (although the errors seemed agnostic to wether or not MKL(FFT) was included).

**Comment by stanmoore1** [comment]
I can reproduce the failures on Intel. However, I believe this is just a compiler issue--unfortunately small differences like optimization level can lead to diverging trajectories (where both are equally valid, similar to changing the starting seed for the pRNG). Unfortunately there isn't an easy fix for this. The "gold standard" log files are based on the GNU compiler, so I would recommend using that for testing.

**Comment by stanmoore1** [comment]
I will put a note in the doc page.

**Comment by ebolandrtx** [comment]
@stanmoore1 which version of GNU? (Does it matter?) I don't want to jump ahead too far an run into the same issue.
