### ISSUE TITLE
SPARTA Manual

### ISSUE THREAD

**Issue by ebolandrtx** [sparta/sparta#348]
## Summary

The link to the PDF manual on the SPARTA website appears to be broken. Can you please repost?

## Type of Issue

'Suggestion for an Enhancement'?

## Detailed Description (Enhancement Suggestion)

SPARTA PDF manual appears to be missing from the website. Is there a specific browser we should use, or does another PDF file need to be posted.

Thanks!

Erin

**Comment by stanmoore1** [comment]
This is now fixed.
