### ISSUE TITLE
Error using Sparta

### ISSUE THREAD

**Issue by federicaportis** [sparta/sparta#364]
## Summary

When I run the simulation all went smoothly but when I use the restart command and i want to rerun the simulation it didn't start and give me this an Error message: Did not assign all restart particles correctly. 

## Type of Issue

It's a 'Bug Report' because I don't know what to do to prevent this kind of error.

## SPARTA Version (Bug Report)

The SPARTA version that I'm using is the June 2016

**Comment by stanmoore1** [comment]
@federicaportis thanks for the report. The 2016 version is pretty old, can you try with the latest patch release (18Jul2022)? Note that there have been several changes to the restart file format, so newer versions of the code cannot read restart files created by older versions of the code, and visa versa.

**Comment by stanmoore1** [comment]
Also if you post a minimal reproducer with everything needed to run we can take a look.

**Comment by stanmoore1** [comment]
@federicaportis any update on this issue?

**Comment by federicaportis** [comment]
Sorry for not answering before, the issue wasn't solved with that 
specific simulation but it wasn't back with other simulations.

Il 2022-12-07 16:25 Stan Moore ha scritto:

**Comment by stanmoore1** [comment]
OK closing for now, please let us know if you see more issues with restarting.
