### ISSUE TITLE
The "compute grid tvib with fix vibmode" warning is erroneous

### ISSUE THREAD

**Issue by aborner1** [sparta/sparta#375]
## Summary

The "Using compute grid tvib with fix vibmode may give incorrect temperature, use compute tvib/grid instead" is erroneous, because it is reported every time _fix vibmode_ is used in conjunction with compute grid, not with _compute grid tvib_.

## Type of Issue

Bug Report

## SPARTA Version 

Current master

## Expected Behavior (Bug Report)

The warning should only appear when the user calls _compute grid tvib_ in conjunction with _fix vibmode_.
https://github.com/sparta/sparta/blob/9b537c74227d32c4a5cffe24ce8a3e630f1f65c5/src/compute_grid.cpp#L200

**Comment by stanmoore1** [comment]
@aborner1 thanks for reporting, I will take a look.
