### ISSUE TITLE
 Surface angular velocity input

### ISSUE THREAD

**Issue by oscillatingion** [sparta/sparta#386]
## Summary

Suggest adding an angular velocity option to the read-surf command.

## Type of Issue

Suggestion

## Detailed Description (Enhancement Suggestion)

Cannot find any keyword option for the “read_surf” command to specify **angular velocities, w_x w_y w_z** for spinning surface.

**Comment by stanmoore1** [comment]
You can use `fix move` to rotate the surface, see 
https://github.com/sparta/sparta/blob/master/examples/surf/in.surf.rotate
https://sparta.github.io/doc/fix_move_surf.html
https://sparta.github.io/doc/move_surf.html

It doesn't have a way to set the angular momentum per se, but it accomplishes the same thing.

**Comment by oscillatingion** [comment]
Dear All,

Thank you so much for finding such a great solution for me.  I do appreciate that!  


Best Regards,
Charles

/* . . . . . . . . . . . . . . . 
    Charles C. Tseng, Ph.D.
    TMAS2  SME | CANVAS Inc.
    Advanced Missile Signature Center
    Arnold Engineering Development Complex
    Arnold AFB, TN 37389-9900
    931-454-4178
              . . . . . . . . . . . . . . . . . . . . . . .  */ 


-----Original Message-----
From: Stan Moore ***@***.***> 
Sent: Monday, February 6, 2023 11:42 AM
To: sparta/sparta ***@***.***>
Cc: TSENG, CHARLES C CTR USAF AFMC AEDC/718TS/TDS ***@***.***>; Author ***@***.***>
Subject: [URL Verdict: Neutral][Non-DoD Source] Re: [sparta/sparta] Surface angular velocity input (Issue #386)

You can use fix move to rotate the surface, see https://github.com/sparta/sparta/blob/master/examples/surf/in.surf.rotate
https://sparta.github.io/doc/fix_move_surf.html
https://sparta.github.io/doc/move_surf.html

It doesn't have a way to set the angular momentum per se, but it accomplishes the same thing.

**Comment by oscillatingion** [comment]
In the input script of "in.surf.rotate," why is the value of nscoll  greatly reduced when the surface starts to rotate (fix 10)?  Could you please provide some explanation for me?   Thank you for your help!   

Best Regards,
Charles

/* . . . . . . . . . . . . . . . 
    Charles C. Tseng, Ph.D.
    TMAS2  SME | CANVAS Inc.
    Advanced Missile Signature Center
    Arnold Engineering Development Complex
    Arnold AFB, TN 37389-9900
    931-454-4178
              . . . . . . . . . . . . . . . . . . . . . . .  */ 


-----Original Message-----
From: Stan Moore ***@***.***> 
Sent: Monday, February 6, 2023 11:42 AM
To: sparta/sparta ***@***.***>
Cc: TSENG, CHARLES C CTR USAF AFMC AEDC/718TS/TDS ***@***.***>; Author ***@***.***>
Subject: [URL Verdict: Neutral][Non-DoD Source] Re: [sparta/sparta] Surface angular velocity input (Issue #386)

You can use fix move to rotate the surface, see https://github.com/sparta/sparta/blob/master/examples/surf/in.surf.rotate
https://sparta.github.io/doc/fix_move_surf.html
https://sparta.github.io/doc/move_surf.html

It doesn't have a way to set the angular momentum per se, but it accomplishes the same thing.
