### ISSUE TITLE
Qusetion about 'adapt_grid' command & 'fix adapt' command

### ISSUE THREAD

**Issue by dltmdals0127** [sparta/sparta#393]
I am a student currently studying the SPARTA DSMC code. As the title suggests, I have a question about the 'adapt_grid' command and the 'fix adapt' command.

In the simulation of plume from orifice, I used the following command to perform a continuous particle number based automatic grid adaptation around the orifice.:

compute test grid all all nrho temp n
fix test ave/grid all 1 100 100 c_test[3]
dump test grid all 100 test_grid.* id f_test
fix adpt adapt 100 all refine value f_test 1 1 file testadapt.* maxlevel 10

However, the child mesh was created only upto 5 levels. even though the number particle per cell became more than 1 (for test purpose). After the fifth adaptation, the grid did not change any more.

Can anyone help me by teaching how to implement a continuous adaptation for this problem?

Thank you. 

Seungmin Lee
MS Student
Gyeongsang National University, South Korea

**Comment by stanmoore1** [comment]
See my reply on the mail list: try compiling with `-DSPARTA_BIGBIG` to increase integer size from 32 bits to 64 bits, which allows the grid to refine further.
