### ISSUE TITLE
Filter

### ISSUE THREAD

**Issue by akestila** [sparta/sparta#398]
## Summary

Is there a possibility in sparta to make a surface act as a particle filter, letting through only particles that having a kinetic energy above a certain value?

## Type of Issue

Question about features

## Detailed Description (Enhancement Suggestion)

A surface that selectively lets through a simulated particle colliding into it based on its kinetic energy - if the particle has a kinetic energy above a certain (user defined) threshold, it will pass through the surface and if it doesn't it will bounce back from the surface.

**Comment by stanmoore1** [comment]
@akestila this feature is not currently available in SPARTA, but could be added as a new `surf_collide` method.

**Comment by akestila** [comment]
Ok, thanks!

**Comment by akestila** [comment]
Ok, thanks!
