### ISSUE TITLE
Cannot use region-style group command to create grid group

### ISSUE THREAD

**Issue by ChienYiYou** [sparta/sparta#402]
## Summary
Dear all

I got "ERROR: Illegal group command" when using group command as follows (the pdf file in link belows contains some images to better describe the problem):

seed	    	    12345
dimension   	    2
global                  gridcut 0.0 comm/sort yes
boundary	            o r p
create_box  	    0 10 0 10 -0.5 0.5  
create_grid 	    10 10 1 clump xyz
balance_grid        rcb cell
region                 upward block  1 3 1 9 -0.5 0.5                      #
group                 upward grid region upward rflag one          # problematic command

And after removing the "region" in group command, 
group               upward grid upward rflag one

The error message didn't show up, and the simulation ran without any other error message.
However, "0 grid cells in group upward" message was shown during the simulation. Therefore, nothing can be computed by compute command requiring grid group as input, such as:
compute           upward pflux/grid upward Ar momxx momyy momzz momxy momyz momxz 

## Type of Issue

Bug Report

## SPARTA Version (Bug Report)

18 Jul 2022 version

## Expected Behavior (Bug Report)

By using region-style group command, a grid group can be created.

## Actual Behavior (Bug Report)

By using region-style group command, a grid group with 0 grid cell was created.

## Further Information, Files, and Links
The file contains: 
1. A pdf file: a description of the problem with some images 
2. A tar file including all it needs to run the simulation (in. file, data. file for surface ...,and output files)
](https://drive.google.com/drive/folders/1NKS-anLfSxVUjBAeg1_or-RV3_MGntGX?usp=sharing)

**Comment by knstmrd** [comment]
You don't need the `rflag` keyword itself;
the command should be `group upward grid region upward one`.
