### ISSUE TITLE
Normal flag in fix_emit_surf

### ISSUE THREAD

**Issue by hieu325** [sparta/sparta#413]
With @Cosimo89, we are testing the subsonic feature of SPARTA. There is an issue we would like to request clarification:

## Summary

In fix_emit_surf.cpp, there are two places where the normalflag is used in opposite ways.

## Type of Issue

Asking for a clear explanation

## Detailed Description (Enhancement Suggestion)
In fix_emit_surf.cpp,
1. The first place where normalflag is used is from line 699 to line 710 inside the function subsonic_inflow().
2. The second place is from line 886 to line 891 inside the function subsonic_grid().
The usage of the surface normal vector seems to be contradictory in these two places. Specifically, when the variable normalflag is false, the first place will compute the inner product between vstream and the normal vector, while the second place will compute the norm/magnitude of vstream.

## SPARTA Version (Bug Report)

18Jul2022

## Expected Behavior (Bug Report)

According to the official documentation, the normalflag is described as follows 

> The normal keyword can be used to alter how velocities are set for added particles. If normal is set to no, then a particle's velocity is set as described above, using the mixture's streaming velocity superposed with a thermal velocity sampled from the temperature of the mixture. Note that the same streaming velocity is used for all emitting surface elements, regardless of their orientation with respect to the streaming velocity. If normal is set to yes, then each surface element is assigned its own "streaming" velocity in the following manner. The streaming velocity points in the direction of the outward normal of the surface element, and its magnitude is set to the magnitude of the mixture's streaming velocity. A velocity is then assigned to the particle in the same manner as before. It is assigned the outward streaming velocity superposed with a thermal velocity sampled from the temperature of the mixture. The effect is that particles effectively stream outward from each emitting surface element.

From my understanding of this description, the first place seems to be wrong, or inconsistent. Can you give an explanation for the implementation in the two places mentioned above?

**Comment by stanmoore1** [comment]
I took a look and it seems very deliberate, I doubt it is a bug. Maybe @sjplimp can comment.

**Comment by sjplimp** [comment]
I am fuzzy on the subsonic code within fix surf/emit - can't recall if I wrote it or someone else, e.g. Michael.

But I think in the first case (around line 700), this is using normalflag to calculate the target # of particles emitted
from a surf, using indot.  When normalflag is set, the emitted particle count is independent of the surf
normal, so indot = maxvstream (same for all surfs).  When normalflag is not set, the emitted particle count becomes smaller as the
surf norm points away from vstream, so indot is smaller, set by the dot product of surf norm with vstream.

In the second case (around line 890), normal is a unit vector pointing in the direction of the flow of emitted
particles from a particular surf.  So if normalflag is set, normal = the surface normal.  If normalflag is not set,
normalflag is the unit vector version of vstream (norm_vstream).  I am unclear on the math in the following
lines for how normal is used with a subsonic target pressure, but I think that is the motivation for how the normal vector
is defined.

Steve

**Comment by stanmoore1** [comment]
@sjplimp thanks for the explanation! @hieu325 @Cosimo89 does that answer your question?

**Comment by sjplimp** [comment]
>> My doubt came from the fact that one could have imagined a different
implementation based on the scalar product between surface orientation and
streaming velocity. For example, by computing the dot product between the
normal and the streaming velocity and applying that magnitude to the
velocity of injected particles at the surface.

I think what you are describing is a third way to do it, different than
either the current "yes" or "no" options.
If you think it is useful in some contexts, we could add it as a third
option.  Maybe with a keyword "yes/reduced"
to indicate the streaming velocity will be in the normal direction but
reduced in magnitude.  But for that case another issue
is what to do if the surf normal and mixture streaming velocity have a
negative dot product, maybe insert no particles?
I think the current "no" option can still insert some particles for that
kind of surf, b/c the thermal component
can overcome the streaming component.

Steve

**Comment by Cosimo89** [comment]
Hi Steve, 
I am not sure if it would be useful to add this third option, as the implementation is clear to me now.
The only suggestion maybe is to add a few lines in the manual to clarify this point (about how the normal injection is defined from the cartesian streaming velocity).

Thank you again,
Cosimo

**Comment by sjplimp** [comment]
ok - sounds good.

The paragraph from the fix emit/surf page is below.
What part do you think is unclear or needs additional explanation?

Steve

--------------

The *normal* keyword can be used to alter how velocities are set for added
particles. If *normal* is set to *no*, then a particle's velocity is set as
described above, using the mixture's streaming velocity superposed with a
thermal velocity sampled from the temperature of the mixture. Note that the
same streaming velocity is used for all emitting surface elements,
regardless of their orientation with respect to the streaming velocity. If
*normal* is set to *yes*, then each surface element is assigned its own
"streaming" velocity in the following manner. The streaming velocity points
in the direction of the outward normal of the surface element, and its
magnitude is set to the magnitude of the mixture's streaming velocity. A
velocity is then assigned to the particle in the same manner as before. It
is assigned the outward streaming velocity superposed with a thermal
velocity sampled fromt he temperature of the mixture. The effect is that
particles effectively stream outward from each emitting surface element.

**Comment by Cosimo89** [comment]
Hi Steve,
Now that I read it again, it actually look very clear!

Apologies for the confusion and thank you for the thorough explanation!

By the way, maybe interesting to give you some context: me and @hieu325 are working on the implementation of a mass flow controlled boundary condition following Liu&Fang approach (just a simple modification of the subsonic pressure inlet boundary). In this approach, we impose a mass flow rate rather than a pressure.

If you think this can add some value to the project, we can maybe open another Issue thread to discuss the implementation and the results from the tests.

Best regards,
Cosimo

**Comment by stanmoore1** [comment]
>If you think this can add some value to the project, we can maybe open another Issue thread to discuss the implementation and the results from the tests.

@Cosimo89 this sounds great. I'll close this issue, please feel free to open another.
