### ISSUE TITLE
Particle count using transparent surface and issue with multiple core processors

### ISSUE THREAD

**Issue by vncntcabalar** [sparta/sparta#418]
## Summary

_Particle count using transparent surface and issue with multiple core processors_

## Type of Issue

_Bug Report_

## SPARTA Version (Bug Report)

_sparta-18Jul2022_

## Expected Behavior (Bug Report)

_A group of particles moving towards the middle of the transparent surface and passing through, we expect that the distribution plot should look like a cosine distribution, with the "peak" or thickest part in the middle of the transparent surface and then becomes thinner as it spreads to both ends._

## Actual Behavior (Bug Report)

_After creating a distribution plot of the data that I have, the plot shows two peaks in the surface, with the middle part having zero recorded particles. This is very far from what we expected a while ago which is the correct distribution to get from this._

_After doing some investigations, I found out that the number of peaks I generate is somewhat related to the number of core processors of the computer that I use in doing simulations. For additional context, I am doing my simulations by parallel processing. I was able to confirm this because the plot with two peaks is generated from my simulations done on my laptop with 2 core processors. Meanwhile, the data and plot that I generated from simulations done on my laboratory's 32-core desktop computer produces 32 peaks across the transparent surface, even if I use the exact same input script with the one I used on my 2-core laptop that produces data with "two peaks"._

## Steps to Reproduce (Bug Report)

_To help you check the issue that I have, I attached here a zipped folder containing the input script that I am using together with the necessary files to run the simulation. I also attached in the folder some sample results that show the issue that I have, including the dump txt files of the particle flux data from simulation run using 1 core, 2 cores, and 4 cores of the processor, and a spreadsheet with the plotted data for visualization._

## Further Information, Files, and Links

[sample_flux.zip](https://github.com/sparta/sparta/files/11645159/sample_flux.zip)

**Comment by knstmrd** [comment]
I took a look at the input file – the issue is that if you run on more than one core, you can't rely on the ordering of the output lines.
So if you add additional surface info to the dump, for example element ID and one of the vertex Y-coordinates, like this
`dump            flux surf subs 200000 Sample_ParticleFlux_2.txt f_flux id v1y`
you can see that the ordering depends on the number of cores you're running on.
So in the plotting/analysis you need use the coordinates that are being output into the file.

**Comment by stanmoore1** [comment]
@knstmrd thanks that is really helpful. @vncntcabalar see this thread for more info: https://sourceforge.net/p/sparta/mailman/message/36773567/.

**Comment by vncntcabalar** [comment]
Thanks to your suggestion @knstmrd, I tried following your suggestion and it actually helped me understand and solve the issue. I am already able to produce the expected results that I need. I am also grateful to you @stanmoore1 for guiding me into this forum and on the SPARTA program.
