### ISSUE TITLE
tce/qk style

### ISSUE THREAD

**Issue by gokulbr4** [sparta/sparta#424]
## Summary

The use of tce/qk style is not providing the mass fraction values. consider if we use 5 species for the simulation like N,NO,N2,O2 and O. In the input script we usually define the fractional value of N2 and O2 for air. Normally when there is a dissociation or exchange reaction takes places this N2 and O2 dissociates into O ,NO and N and this species contains the fractional value after dissociation and exchange but, when the tce/qk style is used the output file shows only the fractional value of N2 and O2 since we defined in the input script itself. The fractional values of N,O and NO in the output file is always zero. which means that there is no dissociation or exchange reaction takes place with the tce/qk style. Kindly ressolve this.

## Type of Issue

Bug Report

## Detailed Description (Enhancement Suggestion)

_Explain how you would like to see SPARTA enhanced, what feature(s) you are looking for, provide references to relevant background information, and whether you are willing to implement the enhancement yourself or would like to participate in the implementation_

## SPARTA Version (Bug Report)

SPARTA Version july 2022

## Expected Behavior (Bug Report)

_Describe the expected behavior. Quote from the SPARTA manual where needed or explain why the expected behavior is meaningful, especially when it differs from the manual_

## Actual Behavior (Bug Report)

_Describe the actual behavior, how it differs from the expected behavior, and how this can be observed. Try to be specific and do **not* use vague terms like "doesn't work" or "wrong result". Do not assume that the person reading this has any experience with or knowledge of your specific research._

## Steps to Reproduce (Bug Report)

_Describe the steps required to quickly reproduce the issue. You can attach (small) files to the section below or add URLs where to download an archive with all necessary files. Please try to create input that are as small as possible and run as fast as possible. NOTE: the less effort and time it takes to reproduce your issue, the more likely, that somebody will look into it._

## Further Information, Files, and Links

_Put any additional information here, attach relevant text or image files and URLs to external sites, e.g. relevant publications_

**Comment by stanmoore1** [comment]
@gokulbr4 do you have a minimal working example that reproduces the issue that we can run? Sorry for the basic question, but are you sure that your simulation conditions are such that would produce reactions? E.g. temperature, density, etc.

**Comment by knstmrd** [comment]
@gokulbr4 I took the input files from the email you sent to the mailing list, could reproduce the issue with no reactions when using the "tce/qk" hybrid style (switching to either "pure" tce or qk leads to reactions taking place).

There is indeed a bug in the `react_tce_qk.cpp` file: in line 126, a check is performed `if (e_excess > 0.0) return 0;` but it is unphysical (and the correct condition that `e_excess >= 0.0` is already being checked for in the base `attempt` function).

There also seem to be two inconsistencies in the code:
1) the base function `attempt` checks that the total energy of the colliding partners is larger than the threshold energy of the reaction. But the QK and TCE styles themselves check for translational+fraction of rotational energy > threshold energy. So  the base check (from `attempt`) can't be re-used, one has to check twice. Related to https://github.com/sparta/sparta/pull/279

2) In `react_tce.cpp`, `react_qk.cpp`, a random number is sampled once, and then the reactions are looped over. In `react_tce_qk.cpp` the reactions are looped over, and a random number is sampled for each reaction to check against.
So if for example 2 reactions occur each having a probability of 0.5, pure tce or qk will sample one of them (as the cumulative probability `react_prob` will be 1). Whereas the hybrid tce/qk approach will sample reaction 1 in 50% of the cases, and in the remaining 50% of the cases will attempt to sample reaction 2, but will do so successfully only with a 0.5 probability. So in the end P(react 1)=0.5, P(react 2)=0.25, P(no react)=0.25 in the `tce_qk` approach (as `react_prob` is reset during each call to `attempt_tce` and `attempt_qk`).

**Comment by gokulbr4** [comment]
Thankyou so much for sorting it out and it is working.
