### ISSUE TITLE
Grid cell corner points on boundary marked as unknown

### ISSUE THREAD

**Issue by pvale80** [sparta/sparta#443]
## Summary

Code (13Apr2023) errors out due to unknown corners of a cell laying on the simulation box (after 2 progressive refinements). 

## Type of Issue

Potentially a bug/issue as it doesn't happen on another machine with a different compiler. 
Currently using: 

Currently Loaded Modulefiles:
 1) slurm   2) amd/aocc/4.0.0   3) amd/aocl/aocc/4.0   4) penguin/openmpi/4.1.4/aocc

Output:

BAD CORNER icell 12936 id 1147186488 type 3 icorner 4 x -3.125000e-05 -6.250000e-05 0.000000e+00 cflags 0 0 0 0
BAD CORNER icell 12936 id 1147186488 type 3 icorner 5 x 0.000000e+00 -6.250000e-05 0.000000e+00 cflags 0 0 0 0
BAD CORNER icell 12936 id 1147186488 type 3 icorner 6 x -3.125000e-05 -3.125000e-05 0.000000e+00 cflags 0 0 0 0
BAD CORNER icell 12936 id 1147186488 type 3 icorner 7 x 0.000000e+00 -3.125000e-05 0.000000e+00 cflags 0 0 0 0
WARNING: Grid cell interior corner points marked as unknown (volume will be wrong if cell is effectively outside) = 4 (../grid.cpp:1908)
ERROR: Grid cell corner points on boundary marked as unknown = 4 (../grid.cpp:1917)

**Comment by stanmoore1** [comment]
@pvale80 can you post a minimum working example, with input script, surface file, etc.? Basically we need everything to run SPARTA, ideally on a single CPU core. Thank you.

**Comment by stanmoore1** [comment]
Closing due to no response, feel free to open a new ticket if needed.
