### ISSUE TITLE
Illegal group command

### ISSUE THREAD

**Issue by MLangner5** [sparta/sparta#445]
## Summary

Hello community.
I'm trying to perform a grid adaption in a certain area of my geometry by defining a region, then a grid group and do the grid adaptation for that grid group but I get an "illegal group command" error.

The commands I use are:

- Define region for the grid adaptation
region cap_exit block 0.25 0.31 -0.01 0.01 -0.001 0.001

- Grid group assignment for later adaptation
group grid_cap_exit grid region cap_exit

## Type of Issue

I am honestly uncertain but I am fairly sure I did everything according to the SPARTA manual and yet I get the "illegal group command" error

## SPARTA Version (Bug Report)

The version is dated to 7th of January 2022

## Expected Behavior (Bug Report)

The manual describes the command as

group ID which style args

Which is prety much what I did with 

group grid_cap_exit grid region cap_exit

## Actual Behavior (Bug Report)

I get the error ERROR: Illegal group command (../grid.cpp:2022) and I don't know how to go from here.
I tried getting rid of the underscores in the IDs, trying a different region and moving the region somewhere else but all possibilities give the same error.

## Steps to Reproduce (Bug Report)

The attached minimal.txt with the geometry file geometry.txt should give the same error, at least they do on my systen.

## Further Information, Files, and Links

[geometry.txt](https://github.com/sparta/sparta/files/13449843/geometry.txt)
[minimal.txt](https://github.com/sparta/sparta/files/13449861/minimal.txt)

Thanks for the help in advance!

**Comment by knstmrd** [comment]
The documentation examples seem to be missing a required argument (for the region group style, you need to specify `rflag `: either `one`, `all`, or `center`). Adding some value fixes this:
`group				grid_cap_exit grid region cap_exit all`

**Comment by stanmoore1** [comment]
@knstmrd thanks for pointing that out. I updated the docs.
