### ISSUE TITLE
Uninitialized variable in stl2surf.py

### ISSUE THREAD

**Issue by alindman** [sparta/sparta#455]
## Summary

When using an stl file that has inconsistent surface normals (some parts of the surface directed inward and some outward), the error output of stl2surf.py attempts to print `dupedge` without it having been initialized.

## Type of Issue

Bug Report

## SPARTA Version (Bug Report)

Version: 7 Jan 2022 (the same logical structure still seems to be present in the up-to-date version at https://github.com/sparta/sparta/blob/7c34abb58e924311e1ec8df1e8778db0f4dbaae6/tools/stl2surf.py) 

I have successfully used this version of Sparta and the same CAD software export to generate working Sparta surface files. 

## Expected Behavior (Bug Report)

I accidentally generated an stl file of a tube that has the surface normal pointing outwards on one section of the tube and inward on another. 
<img width="242" alt="image" src="https://github.com/sparta/sparta/assets/21358940/f662f1bb-422e-4d27-9ea3-cb14ee853791">
I would expect stl2surf to either correct this (which would be very nice!) or issue a descriptive error (also reasonable). 

## Actual Behavior (Bug Report)

Here is the output in my terminal:
```
# of triangles in STL file: 2946
# of vertices in SPARTA file: 1584
# of triangles in SPARTA file: 2946
WARNING: surface is not watertight
Duplicate edge count: 0
Unmatched edge count: 228
One duplicate edge:
Traceback (most recent call last):
  File "/Users/alec/Desktop/Project_8/Phase_IV/sparta/sparta-master/tools/stl2surf.py", line 143, in <module>
    print "One duplicate edge:",dupedge
NameError: name 'dupedge' is not defined
```

The relevant line of code is https://github.com/sparta/sparta/blob/7c34abb58e924311e1ec8df1e8778db0f4dbaae6/tools/stl2surf.py#L151. This attempts to print the variable `dupedge`, which should have been initialized in https://github.com/sparta/sparta/blob/7c34abb58e924311e1ec8df1e8778db0f4dbaae6/tools/stl2surf.py#L128, https://github.com/sparta/sparta/blob/7c34abb58e924311e1ec8df1e8778db0f4dbaae6/tools/stl2surf.py#L133, or https://github.com/sparta/sparta/blob/7c34abb58e924311e1ec8df1e8778db0f4dbaae6/tools/stl2surf.py#L138. 
However, those are all inside if statements that evidently do not get triggered by an otherwise-valid stl with inconsistent surface normals. Thus, `dupedge` never gets initialized and does not exist when the print statement attempts to use it.

## Steps to Reproduce (Bug Report)

Run stl2surf.py with the attached file.

## Further Information, Files, and Links

Here is the stl file that produced the error:
[inconsistent_normals.stl.zip](https://github.com/sparta/sparta/files/14454202/inconsistent_normals.stl.zip)

**Comment by stanmoore1** [comment]
@alindman thank you for the bug report, we will take a look.

**Comment by stanmoore1** [comment]
@alindman this should be fixed by https://github.com/sparta/sparta/pull/457.
