### ISSUE TITLE
Questions about using the output of compute isurf/grid etot

### ISSUE THREAD

**Issue by T0NGXU** [sparta/sparta#462]
## Summary

When we try to use **'compute reduce sum'** to process the output of **'compute isurf/grid etot'** or use this data as the source of **'fix ablate'**, sparta will return **'Caught signal 11 (Segmentation fault: address not mapped to object at address)'**

## Type of Issue

Bug Report

## SPARTA Version (Bug Report)

SPARTA (7 Mar 2024) (same problem in our new version)

## Expected Behavior (Bug Report)

The ablation process is a non-stationary process, so we need to calculate the energy absorbed by the wall timely. In our script, we use **compute isurf/grid etot** as the abaltion source in **fix ablate** command, and use **compute reduce sum** command to calculate the total energy absorbed by wall in a single timestep.

## Actual Behavior (Bug Report)

There are three error messages pointing to the same problem here

1. we use **balance_grid rcb cell** after creating grid, and use **fix ID balance 100 1.001 rcb part flip yes** during the simulation. When the program reaches 100 steps (i.e., when fix balance comes into play), the system immediately gets the following error message and ends
![error_for_bal_grid](https://github.com/sparta/sparta/assets/74865760/22da79ce-2ede-4cf1-b434-8319f8d44c3c)

2. We can change the fix balance mode to dismiss the last error message temporarily, like  **fix ID balance 100 1.001 rcb cell flip yes** .  Then the same error will occur later or even no longer due to the fewer cores used. For example, this error will occur at 279 timestep under mpirun64 but may not occur again under mpirun 4 with same scripts.
![error_for_compute_reduce](https://github.com/sparta/sparta/assets/74865760/7be01f73-f660-41f4-bfeb-4dcab5a5af2a)

3. We can use **fix ID ave/grid group 1 1 c_isurfgrid** to process this data first and then sum it. But this operation is only for the purpose of allowing my program to proceed, and cannot accurately calculate the instantaneous wall absorbed energy for each step, because the fix ave/grid command will have an average of the previous time step results. In this case, since we didnot use compute reduce command again, this empty address error has occurred on the fix abort instruction.
![error_for_fix_ablate](https://github.com/sparta/sparta/assets/74865760/543aa9db-a154-4aef-9c1f-72c32c5b732e)

Summary: Through our analysis, we can find that although error messages appear in multiple places, they are all related to the processing of the **compute isurf/grid** results. And the timestep at which this error message appears is also related to the number of cores used during program execution. Therefore, we speculate that this is an internal bug in Sparta and come here to seek your help

## Steps to Reproduce (Bug Report)

Here is a zip for all files needed to reproduce this issue. We suggest running the in.xuablate.2d script file with 8 or more cores, as some errors may not appear in the 4-core scenario. The script file is set as the error message 1, you can follow the actual behavior to check other error messages. Also, we get comment in this script to help you understand the script and find these errors related command lines.
[reportforgithub.zip](https://github.com/sparta/sparta/files/14626559/reportforgithub.zip)

## Further Information, Files, and Links

None

**Comment by stanmoore1** [comment]
@T0NGXU thank you for filing a bug report, we will take a look.

**Comment by stanmoore1** [comment]
@T0NGXU sorry for the delay. I can reproduce the segmentation fault. Debugging now.

**Comment by stanmoore1** [comment]
@T0NGXU this should be fixed by https://github.com/sparta/sparta/pull/469.
