### ISSUE TITLE
Install Sparta on Windows

### ISSUE THREAD

**Issue by HumbertHumbert7** [sparta/sparta#478]
I'm trying to use Sparta on Windows, but I don't know what do I have to do after having opened the command prompt.
Can you help me? 
Thank you

**Comment by stanmoore1** [comment]
@HumbertHumbert7 currently you need Linux to use SPARTA. That can be accomplished on Windows using either `cygwin`, see https://www.cygwin.com/, or a virtual machine. We currently do not support using SPARTA on Windows directly.

**Comment by rm-tom** [comment]
Hi @HumbertHumbert7 

I recommend doing a dual boot with Linux if you plan to use SPARTA long-term. However, if you absolutely need to use Windows, here are the steps that worked for me. 

### Packages/Dependencies
download cygwin (https://www.cygwin.com/) and install the following packages.

- make
- gcc-g++
- gcc-core (use the same version as gcc-g++)
- libgcc1 (If not automatically installed)
- cmake (not necessary, but could be helpful)

Remember to add cygwin64\bin to your global environment variable list. 

### Serial
1. Update the SPARTA serial makefile under SPARTA/src/MAKE/makefile.serial appropriately (you might be able to use the one I have. See attached file)
2. Open cmd (Powershell doesn't work for some reason) and navigate to the source directory.
3. Make mpi-subs using the command "make mpi-stubs"
4. Make SPARTA serial using the command "make serial"

An executable, "spa_serial.exe," should be created in your source directory. You can run it from the command line using the same steps as a Linux machine. 

### Parallel
1. Download and Install Microsoft MPI (https://www.microsoft.com/en-us/download/details.aspx?id=105289)
2. Add bin to the global environment variable list. 

**Now, it gets slightly weird.**

3. Create a new folder inside your src directory. (e.g. SPARTA/src/MPI) 
4. Navigate to the folder where your MPI library and Includes are located. (Mine are in C:\Program Files (x86)\Microsoft SDKs\MPI). Note that this is separate from the folder where Microsoft MPI's executables are located.
5. Copy the lib, include folders, and paste them inside the MPI folder you create in step 3. The folder contents should have the following files: include\mpi.f90, include\mpi.h, include\mpif.h, include\mpifptr.h, include\mpio.h, include\mspms.h, include\pmibg.h, lib\msmpi.lib, lib\msmpifec.lib, lib\msmpifmc.lib

**Normal steps again**

6. Update SPARTA msmpi makefile under SPARTA/src/MAKE/makefile.msmpi appropriately (Again, you may be able to use the one I have. See attached file)
7. Open cmd and build the appropriate makefile. 
8. You can run a parallel SPARTA from the command line using a syntax like "mpiexec -np 8 spa_msmpi < in.testfile"


### Also
These steps are based on my memory, so I may have forgotten some important points. If you find any issues, feel free to contact me. 
 
I tried getting Kokkos, Nvidia CUDA, and the JPEG library to work in Windows but failed. In the end, I just used Ubuntu for kokkos and cuda, and I got it working in a fraction of the time. But that's probably my lack of knowledge. If you are able to get Kokkos or Cuda to work properly, let me know. 

Github doesn't let me update .serial or .msmpi files, so I've added a text version of the makefile. To make it work normally, modify the filename to make.serial and make.msmpi. 

I hope this helps!

[Makefile_serial.txt](https://github.com/user-attachments/files/15543919/Makefile_serial.txt)
[Makefile_mpi.txt](https://github.com/user-attachments/files/15543920/Makefile_mpi.txt)

**Comment by mgosma** [comment]
Late to the party, but I would also recommend trying Windows Subsystem for Linux (https://learn.microsoft.com/en-us/windows/wsl/). This allows you to run a linux environment (terminal, applications, etc.) without needed to dual boot.

Using this I was able to install Ubuntu and run spa_serial and spa_mpi without issue.

Best of luck!

**Comment by stanmoore1** [comment]
@mgosma good point, thanks!
