### ISSUE TITLE
New relative velocity calculation in collide_vss.cpp

### ISSUE THREAD

**Issue by j-d-fuhr** [sparta/sparta#49]
## Summary

I think I found a bug in CollideVSS::SCATTER_TwoBodyScattering.
When the variable d defined in line 392 is lower than 1.0e-6, it means that the relative velocity in the x direction. The lines 400-402 calculates a wrong new relative velocity.

## Type of Issue

Bug Report

## Detailed Description (Enhancement Suggestion)
Correct code:

```patch
diff --git a/src/collide_vss.cpp b/src/collide_vss.cpp
index 040bb144..7ffaa0a6 100644
--- a/src/collide_vss.cpp
+++ b/src/collide_vss.cpp
@@ -398,8 +398,8 @@ void CollideVSS::SCATTER_TwoBodyScattering(Particle::OnePart *ip,
                                          vrc[0]*vrc[2]*sin(eps))/d );
     } else {
       ua = scale * ( cosX*vrc[0] ); 
-      vb = scale * ( sinX*vrc[1]*cos(eps) ); 
-      wc = scale * ( sinX*vrc[2]*sin(eps) );
+      vb = scale * ( sinX*vrc[0]*cos(eps) ); 
+      wc = scale * ( sinX*vrc[0]*sin(eps) );
     }
   }
```

## SPARTA Version (Bug Report)

I checked this error is still in current git version of collide_vss.cpp

**Comment by stanmoore1** [comment]
I see your point, but I'm still not 100% sure the code is right even with your changes. The if-test is to prevent division by zero when the variable `d` tends to zero, which means the relative velocities in the y and z directions are also tending to zero. If I first take the limit of `vy --> 0` followed by `vz --> 0` then I get your proposed changes. However, if I take the limit of `vz --> 0` first followed by `vy --> 0` then I get a different solution. This code is from Bird's 1994 book, page 36, but there is no discussion of what to do if `d --> 0`. @mgallis can you comment?

**Comment by j-d-fuhr** [comment]
You're right that depending on which component (vy or vz) is first taken the limit to 0 one obtains a different solution. However if one considers that epsilon is a random number between 0 and 2pi, both solutions give the same final relative velocity distribution.

**Comment by stanmoore1** [comment]
Huh, good to know. This does look like a bug, I will submit a PR.

**Comment by stanmoore1** [comment]
I ran this change through the regression testing and it had zero effect on any of the examples, including those with collisions. So either this is a really rare code path, or it isn't captured in our tests. @j-d-fuhr do you have a test case that touches this code?

**Comment by j-d-fuhr** [comment]
The condition d < 10^-6 is in fact very rare, for an isotropic system (the particles velocities have a random orientation) and a mean velocity of (400 m/s) only one on 10^9 collisions satisfy this condition. I would therefore not expect any significant effect. 
I am implementing a homemade very simplified DSMC (homogeneous and isotropic) code for testing clustering algorithms and caught the bug when looking at the code to understand how sparta performed collisions.

**Comment by stanmoore1** [comment]
OK, thanks for reporting the bug.
