### ISSUE TITLE
Seg fault using ps surf_react absorb to a read surfaces file

### ISSUE THREAD

**Issue by bldldodldo** [sparta/sparta#493]
## Summary

Segmentation fault when trying to apply a ps surf_react to a read surface

## Type of Issue

Bug Report

## SPARTA Version (Bug Report)

SPARTA 7 march 2024 version

## Expected Behavior (Bug Report)

We expect SPARTA to not crash and run when applying a "surf_react absorb ps" reaction model to a surface.

## Actual Behavior (Bug Report)

We had first some troubles with the global surfmax (looks like it can't get "1e4" format for a value) because the number of surfaces per cell was a too high. The surface file here has ~60k triangles. 
The run breaks when trying to apply a surf_collide absorb ps. No problem when commented.

What is given in the bash : 

"
[Diavolo:03261] *** Process received signal ***
[Diavolo:03261] Signal: Segmentation fault (11)
[Diavolo:03261] Signal code: Address not mapped (1)
[Diavolo:03261] Failing at address: 0x29
[Diavolo:03261] [ 0] /lib/x86_64-linux-gnu/libc.so.6(+0x42520)[0x7fce0adea520]
[Diavolo:03261] [ 1] /lib/x86_64-linux-gnu/libc.so.6(free+0x1e)[0x7fce0ae4d3fe]
[Diavolo:03261] [ 2] /home/sawen/sparta/src/spa_kokkos_sycl(+0x14ab73)[0x5561cda8db73]
[Diavolo:03261] [ 3] /home/sawen/sparta/src/spa_kokkos_sycl(+0x14ef86)[0x5561cda91f86]
[Diavolo:03261] [ 4] /home/sawen/sparta/src/spa_kokkos_sycl(+0x14f08d)[0x5561cda9208d]
[Diavolo:03261] [ 5] /home/sawen/sparta/src/spa_kokkos_sycl(+0x12faf7)[0x5561cda72af7]
[Diavolo:03261] [ 6] /home/sawen/sparta/src/spa_kokkos_sycl(+0x13003d)[0x5561cda7303d]
[Diavolo:03261] [ 7] /home/sawen/sparta/src/spa_kokkos_sycl(+0x127eb1)[0x5561cda6aeb1]
[Diavolo:03261] [ 8] /home/sawen/sparta/src/spa_kokkos_sycl(+0x127f16)[0x5561cda6af16]
[Diavolo:03261] [ 9] /home/sawen/sparta/src/spa_kokkos_sycl(+0x14505)[0x5561cd957505]
[Diavolo:03261] [10] /lib/x86_64-linux-gnu/libc.so.6(+0x29d90)[0x7fce0add1d90]
[Diavolo:03261] [11] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80)[0x7fce0add1e40]
[Diavolo:03261] [12] /home/sawen/sparta/src/spa_kokkos_sycl(+0x14555)[0x5561cd957555]
[Diavolo:03261] *** End of error message ***
Segmentation fault
"

Same error with different SPARTA builds such as spa_mpi or spa_serial. 
Same error if applying either gs then ps, or just ps, or just gs/ps.

Maybe it has something to do with the great amount of surfaces ? 
UPDATE : I tried with a 44 triangles file, and I get the exact same error.

## Steps to Reproduce (Bug Report)

Run the attached file

Here is a bash command that you can use if you want : 

FILE=in_infinitewire.txt; TIMESTAMP="$(date +%Y-%m-%dT%H-%M-%S)"; echo $TIMESTAMP; mkdir infinitewire_$TIMESTAMP; cp $FILE infinitewire_$TIMESTAMP/; /path/to/your/build/spa_kokkos_sycl -in infinitewire_$TIMESTAMP/$FILE -var t "$TIMESTAMP"

[gas_h_h2_species.txt](https://github.com/user-attachments/files/16162812/gas_h_h2_species.txt)
[gas_h_h2_vss.txt](https://github.com/user-attachments/files/16162814/gas_h_h2_vss.txt)
[gas_surface_reaction.txt](https://github.com/user-attachments/files/16162815/gas_surface_reaction.txt)
[in_infinitewire.txt](https://github.com/user-attachments/files/16162816/in_infinitewire.txt)
[pure_surface_reaction.txt](https://github.com/user-attachments/files/16162817/pure_surface_reaction.txt)
[wire_in_cylinder_data.txt](https://github.com/user-attachments/files/16162818/wire_in_cylinder_data.txt)

**Comment by stanmoore1** [comment]
@bldldodldo thanks, we will take a look.

**Comment by stanmoore1** [comment]
@bldldodldo this should also be fixed by https://github.com/sparta/sparta/pull/505.
