### ISSUE TITLE
couple Sparta and Liggghts

### ISSUE THREAD

**Issue by mpr7366** [sparta/sparta#494]
My name is Madan, and I am currently pursuing my Ph.D. at Western Michigan University. My research focuses on investigating plume-surface interactions during planetary surface landings, a critical aspect of space exploration missions.
I am considering leveraging Sprata and liggghts  to simulate and analyze the landing phenomena in detail. Given their respective strengths—Sprata in handling low density flow  and LIggghts in particle interaction ie. as DEM—I believe that coupling these two tools could provide a comprehensive approach to my research.
However, I am uncertain about the feasibility and methodology of coupling Sprata and liggghts . Specifically, I am interested in:
Feasibility: Is it technically possible to couple Sprata and liggght for integrated simulations of plume-surface interactions?
Existing Tools or Frameworks: Are there any existing tools or frameworks that facilitate the coupling of these two codes? If so, could you provide some guidance or resources on how to implement this coupling effectively?
Best Practices and Challenges: What are the best practices to follow and potential challenges to be aware of when coupling these two simulation tools?
Any insights, resources, or recommendations you could provide would be immensely valuable to my research. Thank you very much for your time and assistance.**

**Comment by stanmoore1** [comment]
@mpr7366 typically one would write a driver program in either C++ or Python and use that to call both SPARTA and LIGGGHTS, and pass information back and forth between the two codes in the driver, see https://sparta.github.io/doc/Section_howto.html#howto_7.

You can build SPARTA as a library and then call functions from a driver program using C++: https://sparta.github.io/doc/Section_start.html#start_4

You can also call SPARTA through the Python interface, see https://sparta.github.io/doc/Section_python.html

**Comment by mpr7366** [comment]
Thanks for the information!

I read the SPARTA manual, and I noticed that the coupling documentation is not published yet. Would you be able to share a coupling example, if possible, so that I can replicate a similar coupling style? I want to focus more on my research objective rather than spending more time figuring out the way to couple SPARTA and LIGGGHTS.

Thanks in advance!

**Comment by stanmoore1** [comment]
>I read the SPARTA manual, and I noticed that the couple/EXAMPLE is not published yet on public version.

LAMMPS coupling examples would be very similar: https://github.com/lammps/lammps/tree/develop/examples/COUPLE.

**Comment by mpr7366** [comment]
Thanks. I will try to replicate. If I need more assistance. I'll continue to ask questions.
