### ISSUE TITLE
header file_ style_( ----------) are missing on the code while  building  sparta as shared library

### ISSUE THREAD

**Issue by mpr7366** [sparta/sparta#498]
Hello,

I'm encountering an issue while trying to build SPARTA. It seems that some header files are missing from the src directory, causing the build to fail. header file like style_surf_react.h and style_region kind of file are missing. 

Running Make.sh with argument: style
[  0%] Built target sparta_PRE_BUILD
Scanning dependencies of target sparta
[  4%] Building CXX object CMakeFiles/sparta.dir/src/domain.cpp.o
[  4%] Building CXX object CMakeFiles/sparta.dir/src/dump_particle.cpp.o
[  4%] Building CXX object CMakeFiles/sparta.dir/src/dump_grid.cpp.o
[  5%] Building CXX object CMakeFiles/sparta.dir/src/dump_image.cpp.o
[  5%] Building CXX object CMakeFiles/sparta.dir/src/dump_movie.cpp.o
[  5%] Building CXX object CMakeFiles/sparta.dir/src/dump_surf.cpp.o
[  5%] Building CXX object CMakeFiles/sparta.dir/src/finish.cpp.o
[  6%] Building CXX object CMakeFiles/sparta.dir/src/error.cpp.o
/home/mpr7366/sparta/src/domain.cpp:446:10: fatal error: style_region.h: No such file or directory
  446 | #include "style_region.h"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/sparta.dir/build.make:505: CMakeFiles/sparta.dir/src/domain.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:195: CMakeFiles/sparta.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by stanmoore1** [comment]
@mpr7366 can you please provide a little more information: what version of SPARTA are you using, and what is the build command you are using? I just tried CMake with the latest version and it built successfully for me. Thank you.

**Comment by mpr7366** [comment]
Hello,
Here are my step:

cd /home/madan/sparta

Copy : Make.sh, make_style.sh and CMakeLists.txt to : Sparta folder

mkdir build
cd build
cmake -C ../cmake/presets/kokkos_mpi_only.cmake -DBUILD_SHARED_LIBS=ON ..
Or

cmake -C ../cmake/presets/kokkos_cuda.cmake -DBUILD_SHARED_LIBS=ON ..

Or

cmake -C ../cmake/presets/mpi.cmake -DBUILD_SHARED_LIBS=ON ..




Using different cmake. I am getting error. Is it possible you to share your step. I am using ubuntu 22.



Regards,

Madan B K



PH.D  student

Research  and Graduate Teaching Assistant

Computational Fluid Dynamics lab(CFD) Lab/Office-C211

Dept. of Mechanical and Aerospace Engineering

Email: ***@***.***

Phone: (269)-779-9477

Webex: https://wmich.webex.com/meet/madan.bk

[cid:7b311e12-1347-4811-ab85-772f0dd87736][cid:faf2faee-c3e0-4c46-8a74-0b7f5b863c89][cid:11112c9d-59cd-47b6-8854-2f31781378e5][cid:2a027462-395f-4731-8f0e-0e690da0c4ae][cid:80231ebc-c894-41f2-9bc3-d929281ca71b]

________________________________

**Comment by stanmoore1** [comment]
You shouldn't need to copy `Make.sh` and `make_style.sh`, I'm not sure what those files do.

You should just be able to 
```
cd sparta
mkdir build
cd build
cmake -C ../cmake/presets/serial.cmake -DBUILD_SHARED_LIBS=ON ../cmake
make 
```

I just tried it on my laptop and had no issues. Be sure to update to latest version of SPARTA if necessary.

**Comment by mpr7366** [comment]
Serial. Make would for me as well.

 using kokkos_cuda.make and MPi.make. Following error pop up.

***@***.***:~/sparta$ mkdir build
uild
***@***.***:~/sparta$ cd build
***@***.***:~/sparta/build$ cmake -C ../cmake/presets/kokkos_cuda.cmake -DBUILD_SHARED_LIBS=ON ..
loading initial cache file ../cmake/presets/kokkos_cuda.cmake
CMake Error: The source directory "/home/madan/sparta" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
***@***.***:~/sparta/build$ cmake -C ../cmake/presets/mpi.cmake -DBUILD_SHARED_LIBS=ON ..
loading initial cache file ../cmake/presets/mpi.cmake
CMake Error: The source directory "/home/madan/sparta" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
***@***.***:~/sparta/build$

Can you be trying using my build command on your end?



Regards,

Madan B K



PH.D  student

Research  and Graduate Teaching Assistant

Computational Fluid Dynamics lab(CFD) Lab/Office-C211

Dept. of Mechanical and Aerospace Engineering

Email: ***@***.***

Phone: (269)-779-9477

Webex: https://wmich.webex.com/meet/madan.bk

[cid:ab985318-2785-406c-81a0-cdc7ba04d308][cid:e6f5c2ea-39bc-4083-aed9-6314b1eee356][cid:af1a5d48-56a2-4447-be8f-ce5788552eef][cid:2e1b24ff-b0fd-493d-b2ce-6379ae66d562][cid:04237afc-4153-48de-8b85-c1e410f39c2a]

________________________________

**Comment by stanmoore1** [comment]
You need to use `../cmake` not `..`, i.e.
```
cd build
cmake -C ../cmake/presets/mpi.cmake -DBUILD_SHARED_LIBS=ON ../cmake
```

This works fine for me with MPI too.

**Comment by mpr7366** [comment]
thank you
