### ISSUE TITLE
"Help Needed: Applying Boundary Conditions for Nozzle Geometry in SPARTA"

### ISSUE THREAD

**Issue by mpr7366** [sparta/sparta#500]
Hi everyone,

I am new to SPARTA and have experience running DSMC simulations using OpenFOAM, but SPARTA seems quite different. I  exported the STL geometry of my nozzle and used stltosurf to make it compatible with SPARTA.

I am trying to simulate a micro nozzle with the following boundary conditions:

Inlet
Outlet
Wall
Axis symmetry
I want particles to emit from the inlet and exit from the outlet. In DSMC Foam, it is possible to define the surface and use it as inlet, outlet, and wall during meshing. How can I do that in SPARTA?

I've attached a diagram of the setup for reference. Can anyone in the community guide me on how to properly apply these boundaries for my nozzle geometry in SPARTA?

Thanks in advance for your help!
![IMG_2581](https://github.com/user-attachments/assets/a11dabbf-fa31-4a8e-b018-316bb19b53ab)

**Comment by stanmoore1** [comment]
@mpr7366 the boundary conditions in SPARTA are described here: https://sparta.github.io/doc/boundary.html.

However this only applies to the box boundaries. For surfaces, you can use `fix emit/surf` (https://sparta.github.io/doc/fix_emit_surf.html) as an inlet, and `surf_collide vanish` as an outlet (https://sparta.github.io/doc/surf_collide.html).

With a combination of these options, I think you can do everything you need. Let us know if you have further questions.

**Comment by mpr7366** [comment]
I created geometry and exported it as stl, then used Sparta's stltosurf program to convert the STL geometry to a surf file, as Sparta recommended. However, for 2D simulation, Sparta does not support triangles created from stl files. Anybody know how to create a 2d geometry directly file like the one shown in the sparta/example, data.cirle?
