### ISSUE TITLE
Some questions about the output of Sparta

### ISSUE THREAD

**Issue by Williamjkevin123** [sparta/sparta#506]
## Summary

I want to know some output of Sparta 

## Type of Issue
As a beginner, just wanna learn some output of sparta programme
```Step CPU Np c_2[1] c_2[2] c_2[3]
       0            0        0            0            0            0
    1000    93.618539    22971 1.0767244e-18   3.0945e-17 6.3947127e-19
    2000    203.92913    24587 1.2021309e-18 3.1512174e-17 3.1522438e-19
    3000    313.84032    25458 1.2886151e-18 3.0772586e-17 4.6381538e-19
    4000     437.4528    25760 1.1861296e-18 3.1076875e-17 2.7098722e-19
    5000    564.03268    26100 1.3391982e-18 3.0739112e-17 5.1363111e-19
    6000    684.22297    26701 1.3839321e-18 3.170305e-17 1.2830295e-19
    7000    795.10176    27109 1.3311678e-18 3.2516244e-17 4.7509908e-19
    8000    909.56416    27228 1.2374797e-18 3.0400514e-17 2.7580106e-19
    9000    1025.9361    27359 9.1602372e-19 3.1029077e-17 4.0093037e-19
   10000    1148.1896    27506 1.0706811e-18 3.1606583e-17 6.3016371e-19
Loop time of 1148.19 on 1 procs for 10000 steps with 27506 particles
```
## Detailed Description (Enhancement Suggestion)
```
Step CPU Np c_2[1] c_2[2] c_2[3]
       0            0        0            0            0            0
    1000    93.618539    22971 1.0767244e-18   3.0945e-17 6.3947127e-19
    2000    203.92913    24587 1.2021309e-18 3.1512174e-17 3.1522438e-19
    3000    313.84032    25458 1.2886151e-18 3.0772586e-17 4.6381538e-19
    4000     437.4528    25760 1.1861296e-18 3.1076875e-17 2.7098722e-19
    5000    564.03268    26100 1.3391982e-18 3.0739112e-17 5.1363111e-19
    6000    684.22297    26701 1.3839321e-18 3.170305e-17 1.2830295e-19
    7000    795.10176    27109 1.3311678e-18 3.2516244e-17 4.7509908e-19
    8000    909.56416    27228 1.2374797e-18 3.0400514e-17 2.7580106e-19
    9000    1025.9361    27359 9.1602372e-19 3.1029077e-17 4.0093037e-19
   10000    1148.1896    27506 1.0706811e-18 3.1606583e-17 6.3016371e-19
Loop time of 1148.19 on 1 procs for 10000 steps with 27506 particles
```
Just wondering what does "Np c_2[1] c_2[2] c_2[3]" mean? and how I can modify the step from smaller" like 100,200....1000" instead of "1000,2000/....."
## SPARTA Version (Bug Report)
SPARTA (7 Mar 2024)

## Actual Behavior (Bug Report)

_Describe the actual behavior, how it differs from the expected behavior, and how this can be observed. Try to be specific and do
## Further Information, Files, and Links

_Put any additional information here, attach relevant text or image files and URLs to external sites, e.g. relevant publications_

**Comment by stanmoore1** [comment]
The stats output is described here: https://sparta.github.io/doc/stats_style.html. For example `Np` is the number of particles, and `c_2[1]` is the first element of a vector output from a compute named "2".

You can change the frequency of output using the `stats` command, see https://sparta.github.io/doc/stats.html.

**Comment by stanmoore1** [comment]
@Williamjkevin123 please also note that the SPARTA mail list is generally better for non-code development questions, simply because more SPARTA users are subscribed to the mail list than on Github.

**Comment by Williamjkevin123** [comment]
Thank you so very much inndeed Stan for your response

**Comment by Williamjkevin123** [comment]
But When I modified stats to 100( originally 1000). the error code comes up(ERROR: Fix used in compute reduce not computed at compatible time (../compute_reduce.cpp:832)) . It's a bit odd
