### ISSUE TITLE
How Can I set the attitude control &altitude of my satellite in Sparta

### ISSUE THREAD

**Issue by Williamjkevin123** [sparta/sparta#507]
## Summary

 Attitude control &Altitude setup 

## Type of Issue

question

## Detailed Description (Enhancement Suggestion)

Hey dear, William here, I  am currently working on Sparta to simmulate the satellite for my thesis. there are two basic questions. the first one is about attitude control setup. have you got any idea how I can set the direction of spacecraft and interpret it into the Sparta? actually I have no clue to get this job done :(. The second is altitude, Could I get it by modifying the Nrho(density) and Temp(temperature). for example, I need the satellite altitude 650km. could I set temp 1500 and nrho to 1.0 etc? Thanks again for your help
## SPARTA Version (Bug Report)

Mar.07.2024

## Expected Behavior (Bug Report)

_Describe the expected behavior. Quote from the SPARTA manual where needed or explain why the expected behavior is meaningful, especially when it differs from the manual_

## Actual Behavior (Bug Report)

_Describe the actual behavior, how it differs from the expected behavior, and how this can be observed. Try to be specific and do **not* use vague terms like "doesn't work" or "wrong result". Do not assume that the person reading this has any experience with or knowledge of your specific research._

## Steps to Reproduce (Bug Report)

_Describe the steps required to quickly reproduce the issue. You can attach (small) files to the section below or add URLs where to download an archive with all necessary files. Please try to create input that are as small as possible and run as fast as possible. NOTE: the less effort and time it takes to reproduce your issue, the more likely, that somebody will look into it._

## Further Information, Files, and Links

_Put any additional information here, attach relevant text or image files and URLs to external sites, e.g. relevant publications_

**Comment by stanmoore1** [comment]
@Williamjkevin123 yes altitude is related to density and temperature. Github issues are more for code development of SPARTA. These questions are more related to science and not really about SPARTA or even DSMC. You could also try posting these questions on the SPARTA Users mail list, see https://sparta.github.io/mail.html, but no guarantees you will get an answer on the mail list. I would suggest you instead talk to your local mentor, e.g. your thesis advisor.

**Comment by Williamjkevin123** [comment]
Thank you so much Stan
