### ISSUE TITLE
Missing "run N time" command functionality

### ISSUE THREAD

**Issue by mgosma** [sparta/sparta#519]
## Summary

Hi,

The current SPARTA user documentation (https://sparta.github.io/doc/run.html) suggests that a simulation can be set to run for a specified amount of physical time, rather than a fixed number of timesteps, by use of the "time" keyword. However, this functionality does not appear in the present code version.

Searching around the GitHub, I have found a few prior commits that appear to have added this functionality (e.g. https://github.com/sparta/sparta/commit/41d36015b621fc0ffb4714d95fe780c871d9ad3a), but these modifications do not appear in the change logs for the relevant files in the master branch.

I was wondering if there was a reason for this functionality not currently existing in the master branch. This would be useful when submitting SPARTA simulations to an HPC cluster with restrictive run time limits (i.e. 8 hours) that necessitate frequent restarts/resubmissions.

Thanks!

## Type of Issue

Question/Suggestion

## SPARTA Version (Bug Report)

4Sep2024

## Expected Behavior (Bug Report)

From the SPARTA manual for the "run" command: 

"Examples:
run 10000
run 1000000 upto
run 100 start 0 stop 1000
run 1000 pre no post yes
run 100000 start 0 stop 1000000 every 1000 "print 'Temp = $t'"
run 100000 every 1000 NULL
run 5.7 time
run 5.7 time every 100 NULL 

Description:
Run or continue a simulation for a specified number of timesteps. If the time keyword is used, run for a specified amount of physical time."

## Actual Behavior (Bug Report)

Attempting to use the "time" keyword currently returns the following error message: "ERROR: Illegal run command (../run.cpp:102)"

## Steps to Reproduce (Bug Report)

Replace the run command from any example file (e.g. in.collide) with the command "run 5.7 time" from the above documentation.

## Further Information, Files, and Links

N/A

**Comment by stanmoore1** [comment]
@mgosma just to clarify, it sounds like you want to run for a specified walltime (e.g. 24 hours), not a specified simulation time (e.g. milliseconds)? I think that option is for simulation time, to be used with variable timestepping since the timestep isn't constant. Not sure why it isn't working, maybe @akstagg can comment.

For walltime, we need to copy `fix halt` from LAMMPS to SPARTA, see https://docs.lammps.org/fix_halt.html. Now that we require C++11 it should be easy--that was the main blocker previously.

**Comment by akstagg** [comment]
@mgosma @stanmoore1 I am looking into this.

**Comment by mgosma** [comment]
Ah yep, my mistake, my original interest was running for a specified walltime. Let me know if you'd me to submit like a separate feature suggestion ticket for that specifically.

**Comment by stanmoore1** [comment]
I talked to the developer of `fix halt` and he said it was fine to copy that from LAMMPS to SPARTA. I will add it to my to-do list.

**Comment by akstagg** [comment]
Also, the "run" documentation contains the old time option (ex: "run 5.7 time" as mentioned above), and all of that description needs to be deleted from run.txt.

**Comment by stanmoore1** [comment]
@mgosma this requested feature should be available in #524.

**Comment by stanmoore1** [comment]
Just to clarify, I removed all references of `run N time` in the documentation, since that feature doesn't actually exist. However, the new `fix halt` supports exiting the run command early using either walltime or simulation time.

**Comment by mgosma** [comment]
@stanmoore1 sounds good. Quick clarification on the "fix_halt" functionality after looking at the LAAMPS docs, does the recorded CPU time reset if I break up my run using the "every" keyword, as it appears to in the stats output? Regardless, look forward to testing this out!
