### ISSUE TITLE
Add run option to automatically identify steady state

### ISSUE THREAD

**Issue by alindman** [sparta/sparta#522]
## Summary

Many simulations should be run "to steady state/equilibrium," so it would be convenient if a run command could be specified to run until some value had reached a plateau and then for some physical time after than.

## Type of Issue

'Suggestion for an Enhancement'

## Detailed Description (Enhancement Suggestion)

Along the lines of https://github.com/sparta/sparta/issues/519 but with a different angle, I often find myself running a simulation a few times for different durations and manually examining output quantities to identify how long it takes to reach a steady state. This is especially tedious/impractical when launching a grid of simulations for a parameter scan, where each one may require a different number of timesteps to equilibrate (well, stabilize - the steady state may be far from physical equilibrium). 

I would like to suggest a new keyword (perhaps `until`?) for the `run` command that allows the user to specify the following:

- A quantity to monitor, like total number of particles, temperature, average speed of particles tallied on a surface, or some other compute
- A gradient (fractional change per time) threshold, like 1% per 10 seconds. When this is reached, a new stats keyword (perhaps `steady`) would change from 0 to 1.
- A sampling window, like 100 timesteps or 0.1 s of physical time. Values of the monitored quantity would be stored in a ring buffer along with their timestamps, and the gradient would be computed at each timestep from the values in the ring buffer.
  - Optionally, there might be cases where it is unnecessary to store the monitored quantity at every timestep. Instead, one could use an `every` argument to sample more sparsely.
- A post-run time (to accumulate statistics) after the stability condition is reached. 
  - This should be able to trigger the start of new outputs (like dump files or images). I'm not sure how to handle that yet. As a temporary solution, the user could filter all the normal outputs by looking for `steady` = 1.
  - In its simplest form, the post-run duration would be a number of steps or amount of physical time. 
  - Even more useful would be a counting/statistical threshold like reaching a certain number of particles tallied on a target surface. 
  - A particularly sophisticated version of the stopping condition would be to track a quantity (or its variance), like the mean speed of particles in a volume. Statistics for this second quantity would only start to accumulate after satisfying the steady-state condition. The most flexible way to specify this would be as a formula.
- Finally, it may be useful to have an over-riding condition, which might be a number of steps, a physical time, or - as in https://github.com/sparta/sparta/issues/519 - a wall time.

Once the specified condition is reached, the run would continue for the statistics-gathering period and then terminate.

The steady-state tracking quantity (either the present value of the gradient, or the present value divided by the target value) should also be a stats option, so the user can observe progress in the terminal. Using the `(present/target)` approach would allow this single value to both track progress towards steady state _and_ serve as the Boolean indicator of whether steady state has been reached (is `(present/target)` smaller than 1?).

An example might be

`run until Np gradient 0.01 per 1 seconds window 10 seconds every 20 steps then_until "c_1[3] > 1000" except_max 1000000 steps`

This would run the simulation until the fractional gradient of the total number of particles per 1 s was less than 1%, based on a ring buffer 20 seconds long containing samples every 20 timesteps. Then, having reached steady state, the run would continue until the compute c_1[3] was larger than 1000, and then end. If the steady-state condition was never reached, the run would terminate after 1000000 steps.

I've included units (`seconds` and `steps`) so it's clear if a time-like quantity is one or the other; there should be a third option for wall time as well.

I suppose some of this behavior may already be present in the LAMMPS `fix halt` that was discussed in #519, but unfortunately I'm not a LAMMPS user so I don't know.

There might be communication overhead in parallel runs depending on what quantity is being tracked, since some quantities require collecting information from all sub-processes. I don't have a clear idea of how significant a bottleneck this might be, but I hope it's small since the communication is one way and only a single value is handed up.

## Further Information, Files, and Links

I suggested a similar tool for MolFlow+ a few years back, which was implemented and is now widely used. I know Sparta doesn't have a GUI (and probably shouldn't), but I think the suggestion above will provide the same basic function - with the added benefit of automatic termination.
https://molflow-forum.web.cern.ch/t/automatic-convergence-testing-and-prediction/398
https://gitlab.cern.ch/molflow_synrad/molflow/-/commit/a75fdb89d4ebd5f79ad85fd6e590eeedebc14088

**Comment by stanmoore1** [comment]
@alindman FYI I'm working on porting `fix halt` from LAMMPS to SPARTA, see https://docs.lammps.org/fix_halt.html. I have it working in SPARTA now but I still need to clean up the code, then I'll submit a pull request. In addition to a walltime limit, you can also check a variable with `fix halt` that could be anything, which makes it quite powerful.

**Comment by stanmoore1** [comment]
@alindman I think #524 adds most if not all of your feature request. You can define a variable that could check for steady state, when that is satisfied abort the current run early, then do another subsequent run to sample properties. If some feature is missing let us know.

**Comment by alindman** [comment]
@stanmoore1 Thanks for implementing this! I look forward to using it.
