### ISSUE TITLE
"Collision cell volume is zero" error

### ISSUE THREAD

**Issue by aborner1** [sparta/sparta#527]
## Summary

For some simulations, in particular 2D axisymmetric ones, it is possible to trigger a "Collision cell volume is zero" error.

## Type of Issue

Bug Report

## SPARTA Version

Latest master as of October 16th, 2024, 6:15pm EDT. [6c1199b](https://github.com/sparta/sparta/commit/6c1199b4bdd2af4fe49024eb9591615e63c7b5f9).
However, this bug has existed for a long time.

## Expected Behavior (Bug Report)

The code should elegantly skip the cells which volume is 0.0, or too close to machine precision 0.

## Actual Behavior (Bug Report)

The code returns an error triggered at line 484 in collide.cpp:

> ERROR on proc 5: Collision cell volume is zero (../collide.cpp:484)

## Steps to Reproduce (Bug Report)

Attached input script and surface file. air.species and air.vss from /data folder. Please run in parallel on 8 threads (should be reproducible due to "comm/sort yes" option). Error should be triggered at step 42319. Takes roughly 30 seconds on 8 threads. Output is also attached.

## Further Information, Files, and Links

A known fix is to add the following line in collide.cpp at line 482:
`if (volume < 1.e-30) continue;`
However, that simply bypasses the problem.

I have verified that the volume of the cell that creates the problem is indeed exactly 0.0, and it contains 6 particles.
I suspect that particles collide with surface which belongs to cell that have a 0.0 volume (i.e., grid cells which are just touched by a surface).

[collision_cell_bug_input.txt](https://github.com/user-attachments/files/17403389/collision_cell_bug_input.txt)
[axi_surf.txt](https://github.com/user-attachments/files/17403351/axi_surf.txt)
[output.txt](https://github.com/user-attachments/files/17403392/output.txt)

**Comment by stanmoore1** [comment]
@aborner1 I ran past 60000 timesteps but it still won't fail on 8 ranks. I'm not doubting there is an issue as you describe, but it may be sensitive to small changes. What compiler/settings are you using?

```
Step CPU Np Nbound Natt Ncoll Ngrid Maxlevel 
       0            0        0        0        0        0      400        1 
   10000    4.5897871    15441        1     1980     1083      493        2 
   20000    7.3545016    37194        3     6201     3357      958        3 
   30000    13.636746    77024       15    14290     7700     2752        4 
   40000     27.68412   154896       20    31564    17167     9658        5 
   50000    57.430972   307675       52    66353    36564    34117        6 
   60000    155.85844   605473      116   134567    74667   115144        7 
```

**Comment by aborner1** [comment]
@stanmoore1 Bummer, I was really hoping this would be reproducible. But the numbers are slightly different from the first adaptation, so it's clearly not using the same random numbers.

I am using mac_mpi with added "-DSPARTA_BIGBIG" and MPICH v4.2.2, with CC=clang.
I suppose I can attempt to reproduce on Linux if it would make it easier for you.

**Comment by stanmoore1** [comment]
@aborner1 if you could try to reproduce with Linux that would be helpful. I'm on RHEL9 with gcc 11.4.1 but have access to other compilers as well.

**Comment by aborner1** [comment]
@stanmoore1 I am struggling to reproduce this on Linux, but I have an understanding of the problem. It is indeed what I described earlier, see image attached (hopefully it is clear). I am going to see whether I can create a very small problem that can trigger the bug.

![Screenshot 2024-10-17 at 2 52 44 PM](https://github.com/user-attachments/assets/04e9b590-1d55-4869-9401-576268222dd4)

**Comment by stanmoore1** [comment]
One thing we could try is putting it in a loop and changing the pRNG seed each time until it fails. 

I know we had trouble in the move algorithm with axisymmetric, currently the code counts the number of times it happens with the `naxibad` metric: https://github.com/sparta/sparta/pull/221. Perhaps we could do something similar for collisions.

**Comment by aborner1** [comment]
The latter (flagging the particle, counting it, deleting it) might be the best way to deal with this. I know it will also be statistically insignificant to remove those particles (just like for the move), because it happens so infrequently, so perhaps that's the best way to get rid of this problem (similar to the bypassing of cells below a certain volume, but less arbitrary than having to choose a volume, which may be a problem for users working on nanoscale simulations).

The pRNG suggestion might be an overkill for this.

One thing I am not 100% certain about is whether it only happens for axisymmetric simulations. I can't recall whether I have encountered it for 3D cases before, but I have at least 3 different instances of it happening for axisymmetric cases that I was able to go back to.

**Comment by stanmoore1** [comment]
>The pRNG suggestion might be an overkill for this.

I mean to reproduce the problem on Linux, not for production.

**Comment by aborner1** [comment]
Also, I must amend what I said earlier and my cartoon. This is for particle-particle collisions, not particle-surface collisions. So there somehow are 6 particles in that cell with a 0 volume, and they collide together. It's rather puzzling.

**Comment by stanmoore1** [comment]
There was also a discussion about this on the SPARTA Users mail list recently. I'd like to understand the issue better.

**Comment by aborner1** [comment]
Just read that thread, sounds exactly the same. The real difficulty is finding a reproducer, since changing platform will reset the RNG.

**Comment by stanmoore1** [comment]
I haven't had any luck reproducing the issue either. I tried on Linux with different RNG seeds, and I tried on a Mac laptop with:

MPICH 4.2.3
Apple clang version 12.0.0 (clang-1200.0.32.29)

**Comment by stanmoore1** [comment]
It fails reliably in a few hundred steps with this:

```
seed 		    12355
dimension 	    2
global 		    gridcut 2e-4 comm/sort yes

boundary 	    s ao p
create_box 	    0 1.41 0 1.5 -0.5 0.5
create_grid 	20 20 1
global          weight cell radius fnum 5.85e17 field constant 1.625 -1 0 0
balance_grid 	rcb cell

read_surf 	    axi_surf.txt

group		    1 surf id 2:92 106
group		    2 surf id 1
group		    3 surf id 93
group	        4 surf id 94:101
group		    5 surf id 102:105

surf_collide    scDif1 diffuse 260 0.875
surf_collide    scDif2 diffuse 260 0.875
surf_collide    scDif3 diffuse 260 0.875
surf_collide    scVan1 vanish
surf_collide    scVan2 vanish
bound_modify    xlo collide scDif1
bound_modify    xhi collide scVan1
surf_modify     1 collide scDif3
surf_modify     2 collide scVan1
surf_modify     3 collide scVan2
surf_modify     4 collide scDif2
surf_modify     5 collide scVan1

species 	    air.species O2
mixture		    mix O2 nrho 2.35e22 vstream -3050.0 0.0 0.0 temp 3000
collide 	    vss all air.vss relax variable

fix             in emit/surf mix 3

create_particles    mix n 0
adapt_grid          all refine surf all 0.00001 iterate 5

compute 	    1 grid all species nrho
compute 	    2 thermal/grid all mix temp
fix		        nrho ave/grid all 10 1000 10000 c_1[*]
fix		        temp ave/grid all 10 1000 10000 c_2[1]
compute 	    MFP lambda/grid f_nrho[*] f_temp lambda knx

timestep 	    2.805e-8

stats		    1
stats_style	    step cpu np nbound nattempt ncoll ngrid maxlevel
stats_modify        flush yes

run 		    1000
```

**Comment by stanmoore1** [comment]
Adding `fix grid/check` flags an issue before a particle gets into a cell with zero volume:

```
ERROR on proc 0: Particle 363175,657521518 on proc 0 is in interior cell 545 on timestep 98 (../fix_grid_check.cpp:178)
```

```
      90    65.542058  6238406     2954  1812112   999707     8536        6 
      91    66.271495  6239475     3064  1812639  1001991     8536        6 
      92    66.999714  6240581     3079  1813089  1001860     8536        6 
      93    67.739299  6241837     3056  1813770  1002563     8536        6 
      94    68.469907  6242938     3090  1814337  1002204     8536        6 
      95    69.199964  6244068     3001  1815149  1001528     8536        6 
      96    69.935922  6245282     2998  1816008  1002944     8536        6 
      97     70.66521  6246515     2974  1816662  1002317     8536        6 
WARNING: 2 particles in wrong cells on timestep 98 (../fix_grid_check.cpp:264)
      98    71.398588  6247681     2957  1817415  1002253     8536        6 
WARNING: 2 particles in wrong cells on timestep 99 (../fix_grid_check.cpp:264)
      99    72.128399  6248867     2933  1818329  1002521     8536        6 
WARNING: 2 particles in wrong cells on timestep 100 (../fix_grid_check.cpp:264)
     100    72.970209  6250176     2940  1818972  1003298     8536        6 
WARNING: 2 particles in wrong cells on timestep 101 (../fix_grid_check.cpp:264)
     101    73.703136  6251506     2892  1819590  1003406     8536        6 
WARNING: 2 particles in wrong cells on timestep 102 (../fix_grid_check.cpp:264)
     102    74.438722  6252752     2932  1820159  1004135     8536        6 
WARNING: 2 particles in wrong cells on timestep 103 (../fix_grid_check.cpp:264)
     103    75.174051  6253992     2919  1820962  1004630     8536        6 
WARNING: 2 particles in wrong cells on timestep 104 (../fix_grid_check.cpp:264)
     104    75.908231  6255308     2872  1821614  1003650     8536        6 
WARNING: 2 particles in wrong cells on timestep 105 (../fix_grid_check.cpp:264)
     105    76.642261  6256524     2845  1822266  1004622     8536        6 
WARNING: 2 particles in wrong cells on timestep 106 (../fix_grid_check.cpp:264)
     106    77.392883  6257635     2752  1823282  1003873     8536        6 
WARNING: 2 particles in wrong cells on timestep 107 (../fix_grid_check.cpp:264)
     107    78.134029  6258871     2764  1824298  1004691     8536        6 
WARNING: 2 particles in wrong cells on timestep 108 (../fix_grid_check.cpp:264)
     108    78.864018  6260047     2844  1825063  1003743     8536        6 
WARNING: 2 particles in wrong cells on timestep 109 (../fix_grid_check.cpp:264)
     109    79.595316  6261217     2757  1825628  1005052     8536        6 
WARNING: 2 particles in wrong cells on timestep 110 (../fix_grid_check.cpp:264)
     110    80.433616  6262490     2784  1826590  1004729     8536        6 
WARNING: 2 particles in wrong cells on timestep 111 (../fix_grid_check.cpp:264)
     111     81.16546  6263777     2781  1827273  1004669     8536        6 
WARNING: 2 particles in wrong cells on timestep 112 (../fix_grid_check.cpp:264)
     112     81.90293  6265082     2752  1827983  1005551     8536        6 
WARNING: 2 particles in wrong cells on timestep 113 (../fix_grid_check.cpp:264)
     113    82.639276  6266325     2702  1829837  1005532     8536        6 
WARNING: 2 particles in wrong cells on timestep 114 (../fix_grid_check.cpp:264)
     114    83.373202  6267650     2666  1830553  1006421     8536        6 
WARNING: 2 particles in wrong cells on timestep 115 (../fix_grid_check.cpp:264)
     115    84.106194  6268771     2606  1831603  1005574     8536        6 
WARNING: 2 particles in wrong cells on timestep 116 (../fix_grid_check.cpp:264)
     116    84.840215  6270066     2614  1832113  1005844     8536        6 
WARNING: 2 particles in wrong cells on timestep 117 (../fix_grid_check.cpp:264)
     117    85.575358  6271262     2696  1833132  1006269     8536        6 
WARNING: 2 particles in wrong cells on timestep 118 (../fix_grid_check.cpp:264)
     118    86.308997  6272642     2635  1834058  1006963     8536        6 
WARNING: 2 particles in wrong cells on timestep 119 (../fix_grid_check.cpp:264)
     119    87.046847  6273981     2571  1834701  1008385     8536        6 
WARNING: 2 particles in wrong cells on timestep 120 (../fix_grid_check.cpp:264)
     120    87.895356  6275378     2558  1835401  1008675     8536        6 
WARNING: 2 particles in wrong cells on timestep 121 (../fix_grid_check.cpp:264)
     121    88.627257  6276636     2566  1836064  1009145     8536        6 
WARNING: 2 particles in wrong cells on timestep 122 (../fix_grid_check.cpp:264)
     122    89.362074  6277827     2542  1836641  1008425     8536        6 
WARNING: 2 particles in wrong cells on timestep 123 (../fix_grid_check.cpp:264)
     123    90.095514  6279155     2423  1837405  1007641     8536        6 
WARNING: 4 particles in wrong cells on timestep 124 (../fix_grid_check.cpp:264)
     124    90.828348  6280427     2458  1838274  1008105     8536        6 
WARNING: 4 particles in wrong cells on timestep 125 (../fix_grid_check.cpp:264)
     125    91.565604  6281718     2521  1839262  1009854     8536        6 
WARNING: 4 particles in wrong cells on timestep 126 (../fix_grid_check.cpp:264)
     126    92.314683  6283055     2382  1840035  1009588     8536        6 
WARNING: 4 particles in wrong cells on timestep 127 (../fix_grid_check.cpp:264)
     127    93.063313  6284246     2502  1840843  1010775     8536        6 
WARNING: 4 particles in wrong cells on timestep 128 (../fix_grid_check.cpp:264)
     128    93.800398  6285688     2361  1842162  1009596     8536        6 
WARNING: 4 particles in wrong cells on timestep 129 (../fix_grid_check.cpp:264)
     129    94.535417  6286900     2392  1843010  1008549     8536        6 
WARNING: 4 particles in wrong cells on timestep 130 (../fix_grid_check.cpp:264)
     130    95.378628  6288073     2444  1844008  1010499     8536        6 
WARNING: 4 particles in wrong cells on timestep 131 (../fix_grid_check.cpp:264)
     131    96.112354  6289411     2336  1844973  1010035     8536        6 
WARNING: 4 particles in wrong cells on timestep 132 (../fix_grid_check.cpp:264)
     132    96.857908  6290827     2325  1846001  1010810     8536        6 
ERROR on proc 0: Collision cell volume is zero (../collide.cpp:481)
```

This looks like some (very rare) bug or roundoff issue with the axisymmetric move.

**Comment by stanmoore1** [comment]
@aborner1 Particles are certainly getting inside the surfaces. Here is a workaround that deletes the bad particles and counts the bad moves in the existing `Axisymm bad moves` category in the logfile output. I'm pretty sure this is just due to roundoff error but want to understand it a bit more before I submit a PR.

```patch
diff --git a/src/update.cpp b/src/update.cpp
index 81428029..99a636dc 100644
--- a/src/update.cpp
+++ b/src/update.cpp
@@ -49,6 +49,7 @@ enum{NCHILD,NPARENT,NUNKNOWN,NPBCHILD,NPBPARENT,NPBUNKNOWN,NBOUND};  // Grid
 enum{TALLYAUTO,TALLYREDUCE,TALLYRVOUS};         // same as Surf
 enum{PERAUTO,PERCELL,PERSURF};                  // several files
 enum{NOFIELD,CFIELD,PFIELD,GFIELD};             // several files
+enum{GUNKNOWN,GOUTSIDE,GINSIDE,GOVERLAP};       // Grid
 
 #define MAXSTUCK 20
 #define EPSPARAM 1.0e-7
@@ -1032,6 +1033,14 @@ template < int DIM, int SURF, int OPT > void Update::move()
               particles[i].flag = PDISCARD;
               naxibad++;
               break;
+            } else if (grid->cinfo[icell].type == GINSIDE) {
+              particles[i].flag = PDISCARD;
+              naxibad++;
+              break;
+            } else if (grid->cinfo[icell].volume == 0.0) {
+              particles[i].flag = PDISCARD;
+              naxibad++;
+              break;
             }
           }
           if (cells[icell].proc != me) particles[i].flag = PDONE;
```

**Comment by stanmoore1** [comment]
@aborner1 I think #528 will fix this issue without needing to delete the particles like in the code above. 

Also I think #528 could also fix https://github.com/sparta/sparta/issues/150 in a better way without needing to delete particles, but I don't have a reproducer for that issue.
