### ISSUE TITLE
fix move/surf bug

### ISSUE THREAD

**Issue by zhangchonglin** [sparta/sparta#56]
## Summary

When running 3D simulation with fix move/surf command, the code crashed in the middle of the simulation.

## Type of Issue

Bug Report

## SPARTA Version

Sparta Version Feb-15 2019

## Expected Behavior
Perform "fix move/surf" for a 3D surface 10 times to rotate it 30 degrees; if run correctly, the operation should finish.

## Actual Behavior
When testing the "fix move/surf" for a 3D surface, the code crashed at the middle of the simulation. In the simulation:
(0) At the beginning, the simulation is run first for 2000 time step to establish a steady state flow field;
(1) 3D surface is rotated for 30 degrees within 10 times;
(2) the interval of surface rotation is 2000 time steps;
(3) total time steps needed for the surface rotation is 20000.
(4) compute grid, compute thermal/grid commands, together with fix ave/grid command are used to sample the flow field information, as shown here, with Nsample=1000.

`compute              1 grid all air n massrho u v w trot tvib`
`compute              2 thermal/grid all air temp press`
`fix                  c1c2 ave/grid all 1 ${Nsample} ${Nsample} c_1[*] c_2[*]`

After about 118 time steps after the first surface rotation (at time step 4118), the code crashed. The crash seems to due to the above fix commands to sample flow field. 

The error output from gdb when the code crashed:
`Program received signal SIGSEGV, Segmentation fault.
0x0000000000431043 in SPARTA_NS::ComputeGrid::compute_per_grid (this=0x164db20) at ../compute_grid.cpp:253
253	        vec[k++] += 1.0;`

When did a quick check in gdb, corresponding to the code shown here:
https://github.com/sparta/sparta/blob/218b1ec5afd4bae5f31721bb5a3da5c5ae9bb1af/src/fix_ave_grid.cpp#L427-L439
 
the output from gdb is shown below. Since `k` is the 2nd dimension in array `tally`, its value should be less than `15` in the current case, but here the value is `24024944`. 
(gdb) info locals
compute = 0x164db20
i = 9
j = 1
k = 24024944
m = 0
n = 2
itally = 15
ntally = 9
kk = 32765
itmp = 0x1589f70
ctally = 0x1e410d0
ntimestep = 4118

Note: 

1. When perform similar simulation with "fix move/surf" in 2D case, the code did not crash;
2. When perform similar simulation with "fix move/surf" using "translate" in 3D, the code also crashed in the middle of the simulation.
3. When "fix                  c1c2 ave/grid all 1 ${Nsample} ${Nsample} c_1[*] c_2[*]" (as in the attached input script) is commented out, the code did not crash. 

## Steps to Reproduce (Bug Report)
The attached file includes:
(1) the minimum input script used to reproduce this issue;
(2) the log file of the simulation.

## Further Information, Files, and Links
File to reproduce the bug: [RotSurf_Orion_Issue.tar.gz](https://github.com/sparta/sparta/files/3045708/RotSurf_Orion_Issue.tar.gz)

**Comment by stanmoore1** [comment]
@zhangchonglin thank you for the detailed bug report. We'll take a look.

**Comment by stanmoore1** [comment]
I can reproduce this on a single MPI rank, it crashed at 4270 timesteps. @sjplimp can you take a look?

**Comment by stanmoore1** [comment]
Here is a full gdb stack trace:

```
#0  0x0000000000463dba in SPARTA_NS::ComputeGrid::compute_per_grid() ()
    at ../compute_grid.cpp:253
#1  0x00000000004e0aa2 in SPARTA_NS::FixAveGrid::end_of_step() ()
    at ../fix_ave_grid.cpp:423
#2  0x0000000000574545 in SPARTA_NS::Modify::end_of_step() ()
    at ../modify.cpp:154
#3  0x00000000005dbea5 in SPARTA_NS::Update::run(int) () at ../update.cpp:265
#4  0x00000000005b5b39 in SPARTA_NS::Run::command(int, char**) ()
    at ../run.cpp:176
#5  0x00000000005632e0 in SPARTA_NS::Input::execute_command() () at ../run.h:17
#6  0x0000000000563a15 in SPARTA_NS::Input::file() () at ../input.cpp:199
#7  0x0000000000570ba6 in main () at ../main.cpp:30
```

**Comment by stanmoore1** [comment]
@zhangchonglin do you know if this is still an issue with the latest version of SPARTA?

**Comment by zhangchonglin** [comment]
@stanmoore1: Thanks for checking! I just checked with the latest commit: e7b60e6, it seem the bug is still there. The code still crashed, although at a slightly earlier time step (time step 4000 for my run with the same input file, corresponding to the first surface rotation time step):

```
#0  0x000000000045a2cf in SPARTA_NS::FixAveGrid::end_of_step (this=0xbe8f60) at ../fix_ave_grid.cpp:501
#1  0x000000000043aeac in SPARTA_NS::Modify::end_of_step (this=0xa58a00) at ../modify.cpp:159
#2  0x00000000005441ce in SPARTA_NS::Update::run (this=0xa38520, nsteps=20000) at ../update.cpp:276
#3  0x0000000000440281 in SPARTA_NS::Run::command (this=0x7fffba6ca070, narg=1, arg=0x205cd80) at ../run.cpp:176
#4  0x0000000000495707 in SPARTA_NS::Input::execute_command (this=0xa38260) at ../run.h:17
#5  0x00000000004925e0 in SPARTA_NS::Input::file (this=0xa38260) at ../input.cpp:199
#6  0x00000000005382e1 in main (argc=3, argv=0x7fffba6ca438) at ../main.cpp:30
```

**Comment by stanmoore1** [comment]
@zhangchonglin there is a high chance this was fixed by #199, can you check again?

**Comment by zhangchonglin** [comment]
Just checked the issue with this commit: 49ef4dd, the issue is fixed. Thanks Stan @stanmoore1

**Comment by stanmoore1** [comment]
Great, thanks!
