### ISSUE TITLE
The continuation problem,read_restart

### ISSUE THREAD

**Issue by wlzx1993** [sparta/sparta#58]
I wanted to use Sparta to continue calculation on the calculation example. Although the calculation file was successfully output, the error <Found no restart file matching pattern> always appeared in the process of re-reading the file.

   I would like the developer to be able to answer questions in the Sparta manual about continuation, preferably with a continuation script in the examples folder.

  But now I'm hoping to get specific answers to my questions about the version of Sparta I'm using now, which is 15Feb19.I will put my detailed description of the problem here.

  This is a two-dimensional cylinder calculation script:

```
 # 2d high speed rarefied flow around a circle Kn=1
restart 10000 flow.%.1  flow.%.2 nfile 4
seed	    	    12345
dimension   	    2
global            gridcut 0.0 comm/sort yes
boundary	       oo ao p
create_box          -2.286 0 0 2.286 -0.5 0.5 
create_grid 	    90 90 1 
balance_grid        rcb cell
global		    nrho 1.699e19 fnum 2.7403171e14 
species		    air.species N2
mixture		    air N2 vstream 7208.75 0.0 0.0 temp 200
fix                 in emit/face air xlo
collide		    vss air air.vss
read_surf           circle.data invert clip
surf_collide	    1 diffuse 1500 1
surf_modify         all collide 1
timestep 	    3.52e-6
#dump                2 image all 50 image.*.ppm type type pdiam 0.002 surf  proc  0.005 size 1024 1024  particle yes  gline yes 0.0001 
#dump_modify	    2 pad 4 
compute    4 surf all all  press etot shx shy 
fix        4  ave/surf all 1 90000 100000 c_4[*]
dump       4 surf all 100000 temp.surf.* id v1x v1y  f_4[*]
stats		    10
stats_style	    step cpu np nattempt ncoll nscoll nscheck
run 		    100000

```
The generated continuation file is `flow.base.1, flow.3.1, flow.2.1, flow.1.1, flow.0.1`.
These five files are the input files for the continuation calculation.

This is a script for the continuation of a two-dimensional cylinder calculation:

```
# 2d high speed rarefied flow around a circle Kn=1
read_restart flow.*.%
seed	    	    12345
balance_grid        rcb cell
species		    air.species N2
fix                 in emit/face air xlo
collide		    vss air air.vss
read_surf           circle.data invert clip
surf_collide	    1 diffuse 1500 1
surf_modify         all collide 1
timestep 	    3.52e-6
#dump                2 image all 50 image.*.ppm type type pdiam 0.002 surf  proc  0.005 size 1024 1024  particle yes  gline yes 0.0001 
#dump_modify	    2 pad 4 
compute    4 surf all all  press etot shx shy 
fix        4  ave/surf all 1 90000 100000 c_4[*]
dump       4 surf all 100000 temp.surf.* id v1x v1y  f_4[*]
# write_restart flow.%.* nfile 4
stats		    10
stats_style	    step cpu np nattempt ncoll nscoll nscheck
run 		    100000
```
The error generated by the operation is `Error on proc 0: Found no restart file matching pattern'
'application called MPI_Abort(MPI_COMM_WORD,1)-process 0`

I hope to get a solution to this problem, or if there is a problem with the script, I hope to be able to point out the wrong place, or give me the correct script file, thank you.

**Comment by stanmoore1** [comment]
@wlzx1993 can you ask this question on the SPARTA mail list instead? https://sparta.sandia.gov/mail.html. There are more SPARTA users there to help, and we want to keep GitHub issues for code bugs and code enhancement requests. Thanks
