### ISSUE TITLE
Additional reaction diagnostics: Breakdown of count of each reaction at end of run

### ISSUE THREAD

**Issue by aborner1** [sparta/sparta#6]
## Summary

Add a feature that list the count of each possible reaction at the end of a run

## Type of Issue

Suggestion for an Enhancement

## Detailed Description (Enhancement Suggestion)

It would be helpful if additional reaction diagnostics, such as the number of occurrences of each gas and surface reactions were listed at the end of a run. That way, the user could quickly visually diagnostic which reactions specified in the chemistry file have a large influence on the results.

**Comment by stanmoore1** [comment]
This could also be implemented as a `fix`, and output to a file.

**Comment by aborner1** [comment]
This has been implemented by @sjplimp in #99 @stanmoore1
