### ISSUE TITLE
Cut3d failed error

### ISSUE THREAD

**Issue by aborner1** [sparta/sparta#7]
## Summary

When refining grid around an object, Cut3d eventually fails and the code returns a segmentation fault.

## Type of Issue

Bug Report

## SPARTA Version (Bug Report)

22Jun18

## Expected Behavior (Bug Report)

Code should be able to refine grid around an object as many times as requested, or at least cleanly exit after returning an error.

## Actual Behavior (Bug Report)

There seems to be an issue with grid->id_find_parent, the code seems to hang in the function just prior to failing.

## Steps to Reproduce (Bug Report)

Run code (serially or in parallel) with input files attached below, should run serially under 2s before returning an error. The run contains no particles, the code is simply asked to refine the grid at every timestep until the error happens. The code needs to be compiled with the BIGBIG flag otherwise the maximum number of grid cells will be overflowed in 32-bits.

## Files to Reproduce

[in-sphere.txt](https://github.com/sparta/sparta/files/2291730/in-sphere.txt)
[data-sphere.txt](https://github.com/sparta/sparta/files/2291731/data-sphere.txt)

**Comment by stanmoore1** [comment]
@aborner1 I can reproduce this. I get a hang and this message: `Cut3d failed in cell ID: 542217403`. Using a printf statement I see that the error flag is:

```
    if (errflag == 2)
      error->one(FLERR,"EF: Singlet BPG edge not on cell face");
```

It is supposed to error out but it never makes it there because it hangs or segfaults in the `failed_cell()` function.

**Comment by aborner1** [comment]
@stanmoore1 I just reproduced this bug with the latest master and it still hangs and returns the Cut3d message.

**Comment by stanmoore1** [comment]
@sjplimp can you take a look?

**Comment by stanmoore1** [comment]
@aborner1 did #97 fix this issue?

**Comment by stanmoore1** [comment]
This still fails with latest master:

```
Step CPU Np 
       0            0        0 
     100 6.8187714e-05        0 
     200 0.00012922287        0 
     300 0.00018811226        0 
     400 0.00024700165        0 
     500 0.00030422211        0 
     600 0.0003631115        0 
     700 0.00042104721        0 
     800 0.00047922134        0 
     900 0.00053811073        0 
Cut3d failed on proc 0 in cell ID: 1073
  lo corner 0.084 0.04 0.02
  hi corner 0.0855 0.0425 0.0225
  # of surfs = 7 out of 606
  surfs: 533 0.0812961 534 0.0812961 537 0.0808713 574 0.0854356 577 0.0851887 578 0.0851887 605 0.0851887
ERROR on proc 0: EF: Singlet BPG edge not on cell face (../cut3d.cpp:611)
```

**Comment by aborner1** [comment]
Can confirm this as well as "No positive volumes in cell" error (which I believe is related) still happen with the latest master. This is the easiest reproducer case I have ever created for this problem.

**Comment by stanmoore1** [comment]
@aborner1 this appears to be a numerical precision issue. You are getting a triangle that is too small to be numerically meaningful. This seems to be from the sphere just barely touching the box bounds in the y and z directions, which makes four minuscule triangles:

```
  1.96262e-17 min triangle edge length
  3.43546e-20 min triangle area
```

If I push out the box bounds by epsilon then it works fine:

```
create_box          0.06 0.09 0.01999999999999999 0.07000000000000001 0.01999999999999999 0.07000000000000001
```

```
  0.00251578 min triangle edge length
  2.74751e-06 min triangle area
```

**Comment by sjplimp** [comment]
@aborner1 @stanmoore1 Alternatively does the problem go away if the sphere is translated by an epsilon different amount so that the clipping does not produce any tiny triangles?  I wonder if there is a better way to clip to avoid epsilon-size triangles?

**Comment by stanmoore1** [comment]
@sjplimp yes translating the sphere by epsilon also works:

```
read_surf data.sphere scale 0.025 0.025 0.025 trans 0.09 0.04500000000000001 0.04500000000000001 clip
```
```
  0.00251578 min triangle edge length
  2.74751e-06 min triangle area
```

**Comment by stanmoore1** [comment]
Translating the other way still makes tiny triangles but they are larger than epsilon, so it succeeds because it has enough numerical precision to do the calcs:

```
read_surf data.sphere scale 0.025 0.025 0.025 trans 0.09 0.04499999999999999 0.04499999999999999 clip
```
```
  7.37615e-17 min triangle edge length
  1.37243e-19 min triangle area
```
